export type Categorie =
  | "verse-vis"
  | "gerookte-vis"
  | "schaal-schelp"
  | "vissalades"
  | "bereid";

export interface Product {
  slug: string;
  naam: string;
  desc: string;
  categorie: Categorie;
  badge?: string;       // MSC | ASC | Biologisch | etc
  omega3?: boolean;
  highlight?: boolean;  // featured border
  bestelId?: string;
  photo?: string;       // lokaal pad in /public (bv. /images/zalm.webp) — leeg = merkillustratie
  // Allergen info (EU-formaat: allergenen HOOFDLETTERS)
  ingredienten: string;
  bevat: string[];
  beschikbaar?: string; // "dagelijks" | "op bestelling" | "seizoensgebonden"
}

export const CATEGORIE_LABELS: Record<Categorie, string> = {
  "verse-vis":    "Verse Vis",
  "gerookte-vis": "Gerookte Vis",
  "schaal-schelp":"Schaal- & Schelpdieren",
  "vissalades":   "Vissalades",
  "bereid":       "Bereid & Snacks",
};

export const CATEGORIE_KLEUR: Record<Categorie, string> = {
  "verse-vis":    "var(--lichtblauw)",
  "gerookte-vis": "var(--gold)",
  "schaal-schelp":"var(--seafoam)",
  "vissalades":   "var(--sand)",
  "bereid":       "var(--salmon)",
};

export const products: Product[] = [
  // ─── VERSE VIS ─────────────────────────────────────────────────────────────
  {
    slug: "kabeljauw",
    naam: "Kabeljauw",
    desc: "Heel gevangen kabeljauw (Gadus morhua) uit de Noordoost-Atlantische Oceaan. Stevige, witte vlees met een milde smaak. De basis van onze kibbeling.",
    categorie: "verse-vis",
    ingredienten: "Kabeljauw (Gadus morhua) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "kabeljauwfilet",
    naam: "Kabeljauwfilet",
    desc: "Verse kabeljauwfilet, zorgvuldig gefileerd en ontgraat. Ideaal om te bakken, stomen of pocheren.",
    categorie: "verse-vis",
    ingredienten: "Kabeljauw (Gadus morhua) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "schol",
    naam: "Schol",
    desc: "Hollandse schol (Pleuronectes platessa), een platvis die bij uitstek thuishoort in onze Noordzee. MSC-gecertificeerd — duurzaam gevangen.",
    categorie: "verse-vis",
    badge: "MSC",
    ingredienten: "Schol (Pleuronectes platessa) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "scholfilet",
    naam: "Scholfilet",
    desc: "Verse scholfilet, ontgraat en schoongemaakt. Licht van smaak, perfect om snel te bakken in boter.",
    categorie: "verse-vis",
    badge: "MSC",
    ingredienten: "Schol (Pleuronectes platessa) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zeetong",
    naam: "Zeetong",
    desc: "De koningin van de Noordzee. Fijnmazig vlees met een delicate, licht zoete smaak. Beschikbaar heel of als filet.",
    categorie: "verse-vis",
    ingredienten: "Zeetong (Solea solea) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zeebaars",
    naam: "Zeebaars",
    desc: "Europese zeebaars (Dicentrarchus labrax), heel of als filet. Stevig wit vlees met een rijke, volle smaak — uitstekend op de grill.",
    categorie: "verse-vis",
    ingredienten: "Zeebaars (Dicentrarchus labrax) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "zeebaarsfilet",
    naam: "Zeebaarsfilet",
    desc: "Verse zeebaarsfilet, perfect gefileerd. Lekker op de huid gebakken met een scheutje olijfolie en citroen.",
    categorie: "verse-vis",
    ingredienten: "Zeebaars (Dicentrarchus labrax) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "dorade",
    naam: "Dorade",
    desc: "Dorade (Sparus aurata), ook wel goudbrasem. Sappig, smaakvol vlees — ideaal om heel te grillen of in de oven te bereiden.",
    categorie: "verse-vis",
    ingredienten: "Dorade (Sparus aurata) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "dorade-filet",
    naam: "Dorade Filet",
    desc: "Verse dorade filet, soepel van structuur met een licht zoete smaak. Snel klaar in de pan.",
    categorie: "verse-vis",
    ingredienten: "Dorade (Sparus aurata) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "griet",
    naam: "Griet",
    desc: "Griet (Scophthalmus rhombus) is een platvis vergelijkbaar met tarbot — iets vettiger van smaak en daardoor zeer geschikt om te stoven.",
    categorie: "verse-vis",
    ingredienten: "Griet (Scophthalmus rhombus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "grietfilet",
    naam: "Grietfilet",
    desc: "Gefileerde griet met boterachtiger vlees dan kabeljauw. Uitstekend gepocheerd of met een romige saus.",
    categorie: "verse-vis",
    ingredienten: "Griet (Scophthalmus rhombus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "tarbot",
    naam: "Tarbot",
    desc: "De tarbot (Psetta maxima) geldt als de meest prestigieuze platvis van de Noordzee. Vast, smaakvol vlees — een echte delicatesse voor feestelijke gelegenheden.",
    categorie: "verse-vis",
    ingredienten: "Tarbot (Psetta maxima) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "tarbotfilet",
    naam: "Tarbotfilet",
    desc: "Vers gefileerde tarbot. Stevig van structuur met een rijke, boterachtiger smaak — weinig bereiding nodig.",
    categorie: "verse-vis",
    ingredienten: "Tarbot (Psetta maxima) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "heek",
    naam: "Heek",
    desc: "Heek (Merluccius merluccius), een slanke zeevis met wit, zacht vlees. Vergelijkbaar met kabeljauw maar fijner van smaak. MSC-gecertificeerd.",
    categorie: "verse-vis",
    badge: "MSC",
    ingredienten: "Heek (Merluccius merluccius) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "heekfilet",
    naam: "Heekfilet",
    desc: "Verse heekfilet: mals, mager en licht van smaak. Uitstekend te bakken, stomen of pocheren.",
    categorie: "verse-vis",
    badge: "MSC",
    ingredienten: "Heek (Merluccius merluccius) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "schelvis",
    naam: "Schelvis",
    desc: "Schelvis (Melanogrammus aeglefinus), naaste familie van de kabeljauw. Licht zoete smaak, wit en mager vlees. Klassiek in Britse fish & chips.",
    categorie: "verse-vis",
    ingredienten: "Schelvis (Melanogrammus aeglefinus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "schelvisfilet",
    naam: "Schelvisfilet",
    desc: "Verse schelvisfilet, dunner en malser dan kabeljauw. Perfect voor een snel, gezond diner.",
    categorie: "verse-vis",
    ingredienten: "Melanogrammus aeglefinus [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "wijting",
    naam: "Wijting",
    desc: "Wijting (Merlangius merlangus) is een fijne witte vis met een delicaat, mals vlees. Snel klaar, makkelijk te bereiden — ideaal voor de lekkerbek.",
    categorie: "verse-vis",
    ingredienten: "Wijting (Merlangius merlangus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "wijtingfilet",
    naam: "Wijtingfilet",
    desc: "Gefileerde wijting — dun, mals en snel klaar. De basis van onze lekkerbek.",
    categorie: "verse-vis",
    ingredienten: "Wijting (Merlangius merlangus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "rode-poon",
    naam: "Rode Poon",
    desc: "Rode poon (Trigla lucerna) met zijn opvallende rode vinnen. Vast, zacht wit vlees dat uitstekend gebakken of gegrild kan worden.",
    categorie: "verse-vis",
    ingredienten: "Rode poon (Trigla lucerna) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "schar",
    naam: "Schar",
    desc: "Schar (Limanda limanda), een kleinere platvis uit de Noordzee. Mager, licht van smaak en betaalbaar — een onderschatte klassieke Hollandse vis.",
    categorie: "verse-vis",
    ingredienten: "Schar (Limanda limanda) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "roodbaars",
    naam: "Roodbaars",
    desc: "Roodbaars (Sebastes marinus) uit de koude Noord-Atlantische Oceaan. Stevig, smaakvol rood vlees — heerlijk gegrild of in de oven.",
    categorie: "verse-vis",
    ingredienten: "Roodbaars (Sebastes marinus) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "haring",
    naam: "Haring",
    desc: "Hollandse Nieuwe haring (Clupea harengus) — gevlinderd of op het broodje. Een Hollandse klassieker, een van de rijkste omega-3 bronnen in ons assortiment.",
    categorie: "verse-vis",
    omega3: true,
    ingredienten: "Haring (Clupea harengus) [VIS]. Geen toegevoegde stoffen. Rauwe haring, conform EU parasietenverordening voorbehandeld.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "varlaks-zalm",
    naam: "Verse Zalm — Varlaks Biologisch",
    desc: "Premium biologische Atlantische zalm (Salmo salar) uit Noord-Noorwegen, boven de poolcirkel. Familieboeren, geen antibiotica, geen GMO. ASC gecertificeerd.",
    categorie: "verse-vis",
    badge: "Biologisch · ASC",
    omega3: true,
    highlight: true,
    bestelId: "varlaks",
    ingredienten: "Atlantische zalm (Salmo salar) [VIS]. Biologisch gecertificeerd. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zalmfilet",
    naam: "Zalmfilet",
    desc: "Verse zalmfilet — mals, rijk van smaak en boordevol omega-3 vetzuren. Wij leveren de Varlaks biologische variant.",
    categorie: "verse-vis",
    badge: "ASC",
    omega3: true,
    bestelId: "varlaks",
    ingredienten: "Atlantische zalm (Salmo salar) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zalmforel",
    naam: "Zalmforel",
    desc: "Zalmforel (Oncorhynchus mykiss) heeft het roze vlees en de rijke smaak van zalm, maar iets milder. Een veelzijdige vis voor grillen of bakken.",
    categorie: "verse-vis",
    ingredienten: "Zalmforel (Oncorhynchus mykiss) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "tonijnfilet",
    naam: "Tonijnfilet",
    desc: "Verse tonijnfilet (Thunnus albacares) — stevig, rood vlees met een vleesvlees karakter. Heerlijk biefstuk-dun gegrild of als sashimi.",
    categorie: "verse-vis",
    ingredienten: "Geelvintonijn (Thunnus albacares) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "zeeduivelfilet",
    naam: "Zeeduivelfilet",
    desc: "Zeeduivel (Lophius piscatorius) — stevig, lobstervlees-achtig wit vlees zonder graat. Perfect voor stoofpotjes, grillen of in een risotto.",
    categorie: "verse-vis",
    ingredienten: "Zeeduivel / Hamvis (Lophius piscatorius) [VIS]. Geen toegevoegde stoffen.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },

  // ─── GEROOKTE VIS ──────────────────────────────────────────────────────────
  {
    slug: "gerookte-zalm-high-seas",
    naam: "Gerookte Zalm — High Seas",
    desc: "Koud gerookte kweekzalm (Salmo salar) uit Noorwegen, lang gesneden in dunne plakken. Van W.G. Den Heijer & Zn. uit Scheveningen. ASC gecertificeerd.",
    categorie: "gerookte-vis",
    badge: "ASC",
    omega3: true,
    bestelId: "zalm-gerookt",
    ingredienten: "Atlantische zalm (Salmo salar) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "gerookte-wilde-zalm",
    naam: "Gerookte Wilde Zalm",
    desc: "Koud gerookte wilde zalm (Oncorhynchus spp.) uit Alaska — dieper van smaak dan kweekzalm. Een echte delicatesse voor bijzondere gelegenheden.",
    categorie: "gerookte-vis",
    omega3: true,
    ingredienten: "Wilde Pacifische zalm (Oncorhynchus spp.) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "gravad-lax",
    naam: "Gravad Lax",
    desc: "Klassiek Scandinavisch gezouten en met dille gekruide zalm. Niet gerookt maar gedroogd met zout, suiker en dille — zijdezacht van textuur.",
    categorie: "gerookte-vis",
    omega3: true,
    ingredienten: "Atlantische zalm (Salmo salar) [VIS], zout, suiker, dille.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "gerookte-bokking",
    naam: "Gerookte Bokking",
    desc: "Warm gerookte haring (Clupea harengus) — een eeuwenoud Hollands product. Volle, rokerige smaak. Zowel heel als als bosje bokking verkrijgbaar.",
    categorie: "gerookte-vis",
    ingredienten: "Haring (Clupea harengus) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "gerookte-forelfilet",
    naam: "Gerookte Forelfilet",
    desc: "Warm gerookte forelfilet (Oncorhynchus mykiss) — delicaat, mild rokerig en rijk van smaak. Heerlijk op een broodje of in een salade.",
    categorie: "gerookte-vis",
    ingredienten: "Forel (Oncorhynchus mykiss) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "gerookte-heilbot",
    naam: "Gerookte Heilbotfilet",
    desc: "Fijnmazig, vet gerookt heilbotvlees (Hippoglossus hippoglossus) — bijna boterarchtig van textuur. Een echte delicatesse op een borrelplank.",
    categorie: "gerookte-vis",
    ingredienten: "Heilbot (Hippoglossus hippoglossus) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "gerookte-kipper",
    naam: "Gerookte Kipper",
    desc: "Traditioneel gerookte haring, gespleten en koud gerookt. De kipper is een van de oudste conserveringsmethoden voor vis.",
    categorie: "gerookte-vis",
    ingredienten: "Haring (Clupea harengus) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "bosje-sprot",
    naam: "Bosje Sprot",
    desc: "Gerookte sprot (Sprattus sprattus) — kleine vette visjes met een intense, rokerige smaak. Uitstekend als borrelhapje of op donker brood.",
    categorie: "gerookte-vis",
    ingredienten: "Sprot (Sprattus sprattus) [VIS], zout, rook.",
    bevat: ["VIS"],
    beschikbaar: "dagelijks",
  },

  // ─── SCHAAL- & SCHELPDIEREN ────────────────────────────────────────────────
  {
    slug: "hollandse-garnalen",
    naam: "Hollandse Garnalen",
    desc: "Dagverse Noordzeegarnalen (Crangon crangon) van Heiploeg & SOLT — gevangen door de traditionele garnalenvloot, dagelijks gekookt en gepeld aan de Waddenkust. MSC-gecertificeerd sinds 2017.",
    categorie: "schaal-schelp",
    badge: "MSC",
    bestelId: "garnalen-hollands",
    ingredienten: "Hollandse garnalen (Crangon crangon) [SCHAALDIEREN], zout. Kan conserveermiddel E223 bevatten [SULFIET].",
    bevat: ["SCHAALDIEREN", "SULFIET"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "noorse-garnalen",
    naam: "Noorse Garnalen",
    desc: "Noorse garnalen (Pandalus borealis) uit de koude Noord-Atlantische Oceaan — gepeld en direct klaar voor gebruik. Klein, zoet en mals van smaak.",
    categorie: "schaal-schelp",
    ingredienten: "Noorse garnalen (Pandalus borealis) [SCHAALDIEREN], zout. Kan conserveermiddel (E221) bevatten.",
    bevat: ["SCHAALDIEREN"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "franse-gambas",
    naam: "Franse Gamba's",
    desc: "Grote, verse gamba's (Penaeus vannamei) — stevig van textuur en vol van smaak. Perfect om te grillen of te bakken in knoflookolie.",
    categorie: "schaal-schelp",
    ingredienten: "Gamba's (Litopenaeus vannamei) [SCHAALDIEREN]. Geen toegevoegde stoffen.",
    bevat: ["SCHAALDIEREN"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "gekookte-gambas",
    naam: "Gekookte Gamba's (Crevettes)",
    desc: "Voorgekookte en gekoelde gamba's — direct klaar om te eten. Heerlijk bij een borrel met dipsaus of in een salade.",
    categorie: "schaal-schelp",
    ingredienten: "Gamba's (Penaeus spp.) [SCHAALDIEREN], water, zout.",
    bevat: ["SCHAALDIEREN"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zeeuwse-mosselen",
    naam: "Zeeuwse Mosselen",
    desc: "Verse Zeeuwse mosselen (Mytilus edulis) — gekweekt in de schone Zeeuwse wateren. Van nature met de seizoenen, het lekkerst van augustus tot april.",
    categorie: "schaal-schelp",
    ingredienten: "Mosselen (Mytilus edulis) [WEEKDIEREN].",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "creuse-oesters",
    naam: "Creuse Oesters",
    desc: "Franse creuse oesters (Crassostrea gigas) — zout, fris en romig van smaak. Wij leveren per dozijn. Vraag naar de maat van de dag.",
    categorie: "schaal-schelp",
    ingredienten: "Oesters (Crassostrea gigas) [WEEKDIEREN].",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "kokkels",
    naam: "Kokkels",
    desc: "Verse Zeeuwse kokkels (Cerastoderma edule) — een Hollands borrelhapje bij uitstek. Zout, zeers en vol van smaak.",
    categorie: "schaal-schelp",
    ingredienten: "Kokkels (Cerastoderma edule) [WEEKDIEREN], zout, azijn.",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "coquilles",
    naam: "Coquilles",
    desc: "Verse coquilles (Pecten maximus) — mals en licht zoet van smaak. Binnen 2 minuten klaar in de pan. Ideaal als voorgerecht of borrelschotel.",
    categorie: "schaal-schelp",
    ingredienten: "Coquilles (Pecten maximus) [WEEKDIEREN].",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "krabklauwen",
    naam: "Krabklauwen",
    desc: "Voorgekookte krabklauwen — vol smaak en direct klaar. Heerlijk met een citroenbotersausje of als onderdeel van een visplankje.",
    categorie: "schaal-schelp",
    ingredienten: "Krab (Cancer pagurus) [SCHAALDIEREN], zout, water.",
    bevat: ["SCHAALDIEREN"],
    beschikbaar: "op bestelling",
  },
  {
    slug: "inktvis",
    naam: "Inktvis",
    desc: "Verse inktvis (Loligo vulgaris) — schoongemaakt en klaar voor de bereidng. Lekker op de grill, als fritto misto of in een stoofpot.",
    categorie: "schaal-schelp",
    ingredienten: "Inktvis (Loligo vulgaris) [WEEKDIEREN]. Geen toegevoegde stoffen.",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "seizoensgebonden",
  },
  {
    slug: "scheermessen",
    naam: "Scheermessen",
    desc: "Verse scheermessen (Ensis directus) — een bijzondere Noordzee-delicatesse. Snel te bereiden en heerlijk met look en peterselie.",
    categorie: "schaal-schelp",
    ingredienten: "Scheermessen (Ensis directus) [WEEKDIEREN].",
    bevat: ["WEEKDIEREN"],
    beschikbaar: "seizoensgebonden",
  },

  // ─── VISSALADES ────────────────────────────────────────────────────────────
  {
    slug: "zalmsalade",
    naam: "Zalmsalade",
    desc: "Huisgemaakte zalmsalade van verse zalm, mayonaise, ui en kruiden. Heerlijk op brood of als borrelhapje.",
    categorie: "vissalades",
    ingredienten: "Zalm [VIS], mayonaise (zonnebloemolie, EIEREN, azijn, MOSTERD), ui, dille, zout, peper.",
    bevat: ["VIS", "EIEREN", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "krabsalade",
    naam: "Krabsalade",
    desc: "Verse krabsalade met surimi of echte krab, romige mayonaise en lenteui. Fris en smaakvol.",
    categorie: "vissalades",
    ingredienten: "Krab / surimi [VIS, SCHAALDIEREN], mayonaise (EIEREN, MOSTERD), lenteui, zout, paprika.",
    bevat: ["VIS", "SCHAALDIEREN", "EIEREN", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "tonijnsalade",
    naam: "Tonijnsalade",
    desc: "Klassieke tonijnsalade van tonijn uit blik, verse mayonaise, ui en augurk. Veelzijdig op brood of als snack.",
    categorie: "vissalades",
    ingredienten: "Tonijn (Thunnus albacares) [VIS], mayonaise (EIEREN, MOSTERD), ui, augurk, zout, peper.",
    bevat: ["VIS", "EIEREN", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "garnalensalade",
    naam: "Garnalensalade",
    desc: "Verse garnalensalade van Hollandse Noordzeegarnalen met huisgemaakte cocktailsaus. Romig, zoet en licht pittig.",
    categorie: "vissalades",
    ingredienten: "Hollandse garnalen (Crangon crangon) [SCHAALDIEREN], mayonaise (EIEREN, MOSTERD), cocktailsaus (tomatenpuree, suiker, citroensap), zout.",
    bevat: ["SCHAALDIEREN", "EIEREN", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "zeewiersalade",
    naam: "Zeewiersalade (Wakame)",
    desc: "Frisse wakame zeewiersalade met sesamolie en sojasaus — een Japanse klassieker die uitstekend past bij gerookte vis.",
    categorie: "vissalades",
    ingredienten: "Wakame zeewier (Undaria pinnatifida), sesamolie, SOJA saus (water, sojabonen [SOJA], tarwe [GLUTEN], zout), azijn, suiker, sesamzaad [SESAMZAAD].",
    bevat: ["SOJA", "GLUTEN", "SESAMZAAD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "visschaal",
    naam: "Visschaal / Vistrio op Bestelling",
    desc: "Een samengestelde visschotel naar wens — gerookte vis, salades, schaal- en schelpdieren. Ideaal voor feestjes en borrels. Inhoud in overleg.",
    categorie: "vissalades",
    bestelId: "feestschotel",
    ingredienten: "Wisselende selectie VIS, SCHAALDIEREN en/of WEEKDIEREN, diverse sauzen en garneringen. Bevat EIEREN, MOSTERD. Kan GLUTEN en MELK bevatten. Samenstelling in overleg.",
    bevat: ["VIS", "SCHAALDIEREN", "WEEKDIEREN", "EIEREN", "MOSTERD"],
    beschikbaar: "op bestelling",
  },

  // ─── BEREID & SNACKS ───────────────────────────────────────────────────────
  {
    slug: "kibbeling",
    naam: "Kibbeling",
    desc: "Knapperig gebakken stukjes witvis in een luchtig, goudbruin beslag — dé Hollandse klassieker. Wij maken kibbeling van kabeljauw (rijkere smaak) óf pollak (MSC, mild). Vraag naar de vis van de dag.",
    categorie: "bereid",
    bestelId: "kibbeling-pollak",
    ingredienten: "Witvis (kabeljauw Gadus morhua of pollak Theragra chalcogramma) [VIS], TARWEBLOEM, water, zout, rijsmiddel (E450, E500), plantaardige olie. Bereid in frituurvet. Knoflooksaus: mayonaise (EIEREN, MOSTERD).",
    bevat: ["VIS", "GLUTEN (tarwe)", "EIEREN", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "lekkerbek",
    naam: "Lekkerbek",
    desc: "Verse wijting gehuld in een luchtig, knapperig beslag. Wijting is een magere, fijne witte vis — vergelijkbaar met kabeljauw maar iets subtieler van smaak.",
    categorie: "bereid",
    bestelId: "lekkerbek",
    ingredienten: "Wijting (Merlangius merlangus) [VIS], TARWEBLOEM, water, zout, rijsmiddel, plantaardige olie. Bereid in frituurvet.",
    bevat: ["VIS", "GLUTEN (tarwe)"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "broodje-haring",
    naam: "Broodje Haring",
    desc: "Rauwe Hollandse Nieuwe haring op een zacht broodje met fijngehakte ui en knapperige augurk. Een van de voedzaamste producten in ons assortiment.",
    categorie: "bereid",
    omega3: true,
    bestelId: "haring",
    ingredienten: "HARING (Clupea harengus) [VIS], broodrol (TARWEBLOEM, gist, water, zout) [GLUTEN], ui, augurk (komkommer, azijn, suiker, MOSTERD), zout.",
    bevat: ["VIS", "GLUTEN (tarwe)", "MOSTERD"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "vissoep",
    naam: "Vissoep",
    desc: "Dagelijks vers bereid in onze eigen keuken. Samenstelling wisselt op basis van het seizoensaanbod — altijd met verse vis als basis. Vol smaak, warm en voedzaam.",
    categorie: "bereid",
    bestelId: "vissoep",
    ingredienten: "Verse vis (wisselend) [VIS], water, ui, wortel, SELDERIJ, prei, aardappel, kruiden, zout. Kan room [MELK] bevatten.",
    bevat: ["VIS", "SELDERIJ", "kan MELK bevatten"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "vispotje",
    naam: "Vispotje",
    desc: "Een romig stoofpotje met verse stukken vis in een rijke saus. Ideaal als uitgebreid tussendoortje of lichte maaltijd. De vissoort wisselt met het seizoen.",
    categorie: "bereid",
    ingredienten: "Verse vis (wisselend) [VIS], kookroom [MELK], ui, wortel, SELDERIJ, kruiden, zout, peper.",
    bevat: ["VIS", "MELK", "SELDERIJ"],
    beschikbaar: "dagelijks",
  },
  {
    slug: "feestschotel",
    naam: "Feestelijke Visschotel",
    desc: "Een indrukwekkende schaal met een selectie van onze beste producten — perfect voor bijzondere gelegenheden, borrels of een feestelijk diner. Inhoud en grootte in overleg.",
    categorie: "bereid",
    bestelId: "feestschotel",
    ingredienten: "Wisselende selectie verse en gerookte VIS, SCHAALDIEREN en/of WEEKDIEREN, diverse sauzen. Kan EIEREN, GLUTEN en MELK bevatten.",
    bevat: ["VIS", "SCHAALDIEREN", "WEEKDIEREN", "kan EIEREN, GLUTEN, MELK bevatten"],
    beschikbaar: "op bestelling",
  },
];
