import type { BlogPost } from "./blog";
/** Reviewed source corrections: no unverified quotations, stock promises or blanket sustainability claims. */
export const BLOG_CORRECTIONS:Record<string,Partial<BlogPost>>={
 "verse-vis-bewaren-en-bereiden-tips":{secties:[
 {alineas:["Verse vis vraagt om zorgvuldig vervoer, koeling en bereiding. Volg altijd het bewaaradvies bij aankoop en de informatie op de verpakking."]},
 {kop:"Versheid en veiligheid zijn niet hetzelfde",alineas:["Geur en uiterlijk helpen bij het beoordelen van kwaliteit, maar bewijzen niet dat vis veilig is.","Ruikt de vis onaangenaam of twijfelt u aan de bewaring? Eet hem niet en vraag advies."]},
 {kop:"Bewaren in de koelkast",alineas:["Neem vis in een koeltas mee en leg hem thuis direct afgedekt in de koelkast bij 4°C. Eet onverpakte verse vis bij voorkeur op de dag van aankoop.","Respecteer de te-gebruiken-tot-datum. Houd rauwe vis gescheiden van klaar eten; ziekmakende bacteriën zijn niet altijd te zien of te ruiken."]},
 {kop:"Invriezen en ontdooien",alineas:["Vraag of het product geschikt is om thuis in te vriezen en of het eerder is ontdooid. Verpak goed en volg het productadvies.","Ontdooi afgedekt in de koelkast, niet op het aanrecht. Eerder invriezen alleen bewijst geen geschiktheid voor rauwe consumptie."]},
 {kop:"Gaarheid controleren",alineas:["Werk met schoon keukengerei en voorkom kruisbesmetting. Gaar rauwe vis door en door; tijd alleen is geen bewijs van gaarheid.","De benodigde tijd hangt af van dikte en bereiding. Vraag ons om advies voor uw filet."]},
 {kop:"Extra aandacht voor kwetsbare groepen",alineas:["Zwangeren, jonge kinderen, ouderen en mensen met verminderde weerstand vermijden rauwe vis en niet volledig verhitte gerookte vis. Voor zwangeren geldt bovendien apart advies over vissoorten.","Lees de adviezen van het Voedingscentrum of bespreek persoonlijke vragen met een zorgverlener."]}
 ],gerelateerdeLinks:[{label:"Het assortiment",href:"/assortiment"},{label:"De viskalender",href:"/viskalender"},{label:"Voedingscentrum: veilig omgaan met vis",href:"https://www.voedingscentrum.nl/nl/thema/5xveilig/vis.aspx"},{label:"Voedingscentrum: bewaren, bereiden en voedingsadvies",href:"https://www.voedingscentrum.nl/encyclopedie/vis.aspx"}]},
 "echt-gerookte-vis-vs-kunstmatige-rooksmaak":{title:"Gerookte vis en rookaroma: wat is het verschil?",excerpt:"Roken en toegevoegd rookaroma zijn verschillende bereidingswijzen. Lees het etiket en vraag hoe uw product is gemaakt.",secties:[
 {alineas:["Gerookte zalm, makreel en bokking hebben ieder hun eigen smaak en structuur. De manier van produceren verschilt per product. Het etiket en de informatie van de leverancier geven meer houvast dan alleen de kleur of prijs."]},
 {kop:"Koud en warm roken",alineas:["Bij koud roken wordt de vis gerookt zonder hem zoals bij koken of bakken door en door te garen. Warm roken gebruikt meer warmte en kan de vis tegelijk garen.","De precieze werkwijze en bewaarbaarheid horen bij het specifieke product. Ga niet ervan uit dat elke gerookte vis al volledig gaar is."]},
 {kop:"Toegevoegd rookaroma",alineas:["Rookaroma wordt als ingrediënt gebruikt om rooksmaak toe te voegen. Dat is een andere productiemethode dan het product aan rook blootstellen.","De ingrediëntenlijst kan rookaroma vermelden. Een andere smaak of prijs bewijst op zichzelf niet hoe een product is gemaakt; vraag uitleg bij onduidelijkheid."]},
 {kop:"Zo krijgt u duidelijkheid",alineas:["Lees de ingrediënten, het etiket en het bewaaradvies. Ook echt gerookte producten kunnen andere ingrediënten bevatten; ‘alleen vis, zout en rook’ is geen algemene regel.","Vraag uw visboer naar de leverancier en de bereidingswijze. Herkomst, roken en certificering zijn afzonderlijke vragen."]},
 {kop:"Gerookte vis bij Schaap’s",alineas:["In ons assortiment vindt u onder meer gerookte zalm en makreel. Vraag aan de toonbank naar de actuele productinformatie en beschikbare varianten.","Kies voor een salade, broodje of recept de vis die daarbij past. Houd gerookte vis gekoeld en volg het bewaaradvies. Voor kwetsbare groepen geldt extra voorzichtigheid met niet volledig verhitte gerookte vis."]}
 ]}
 ,
 "sinds-1938-de-geschiedenis-van-schaaps-vis":{title:"Sinds 1938: generaties vis op de Herenstraat",secties:[
 {alineas:["Wie op de Herenstraat in Leiden loopt, merkt misschien verse vis, gebakken kibbeling en gerookte makreel al op voordat hij de winkel ziet. Op nummer 48 zit Schaap’s Vishandel sinds 1938. Dit is het verhaal van een zaak die generaties Leidenaren heeft bediend."]},
 {kop:"1938 — Gerrit Schaap begint",alineas:["Gerrit Schaap opent zijn vishandel in een tijd waarin buurtviswinkels bij het dagelijks leven in Leiden horen. Zijn naam blijft aan de winkel verbonden, tot op de dag van vandaag."]},
 {kop:"1957 — De familie Haasnoot neemt over",alineas:["Cor Haasnoot begint als dertienjarige bij meneer Schaap en leert het vak van onderaf. In 1957 neemt hij de zaak over. De naam Schaap blijft als eerbetoon aan de oprichter; zo wordt de familie Haasnoot in vis-etend Leiden met deze naam verbonden."]},
 {kop:"2009 — De derde generatie",alineas:["In 2009 neemt de derde generatie het roer officieel over. De winkel gaat mee met de tijd en behoudt de persoonlijke, gezellige sfeer die klanten waarderen. Bij een bezoek horen advies en een gesprek, naast de vis."]},
 {kop:"2018 — Tachtig jaar herinneringen",alineas:["Op 1 januari 2018 bestaat de zaak tachtig jaar. Klanten sturen foto’s en herinneringen in voor een jubileumboek. Het laat zien hoe de winkel deel uitmaakt van het dagelijks leven in de stad."]},
 {kop:"Vandaag — klaar voor de vierde generatie",alineas:["Naast de winkel aan de Herenstraat staat het team op de Leidse markt op woensdag en zaterdag en bij Hoogvliet in Voorschoten op vrijdag. Het assortiment is gegroeid en de website is erbij gekomen, maar de kern blijft: verse vis, eerlijk advies en een goed gesprek."]}
 ]},
 "hollandse-nieuwe-waarom-juni-haring-anders-smaakt":{excerpt:"Elk jaar in juni verwelkomt Nederland de nieuwe haring. Wat maakt Hollandse Nieuwe bijzonder? Zijn zachte, romige structuur.",secties:[
 {alineas:["Haring is er het hele jaar. Hollandse Nieuwe markeert de start van het nieuwe seizoen, traditioneel in juni. De precieze start hangt af van de vis en wordt elk jaar bekendgemaakt."]},
 {kop:"Vol van smaak op het juiste moment",alineas:["In het voorjaar eet de haring plankton in de Noordzee en bouwt vetreserves op vóór de voortplanting. De vis die voor Hollandse Nieuwe wordt gekozen heeft het vetgehalte dat nodig is voor de kenmerkende romige structuur.","Ook de traditionele bereiding en rijping zijn belangrijk. De haring wordt gekaakt, waarbij de alvleesklier blijft zitten; de enzymen helpen de zachte structuur te ontwikkelen. Niet elke verse haring die in juni wordt verkocht is dus automatisch Hollandse Nieuwe."]},
 {kop:"Zo eet u hem",alineas:["Sommigen eten haring graag puur, hooguit met gesnipperde ui. Anderen kiezen een zacht broodje met augurk. U kunt hem traditioneel bij de staart vasthouden of in stukjes laten snijden.","In onze winkel en op de markt maken we de haring klaar wanneer u hem komt halen. Zo blijft de portie vers in plaats van gesneden stukken uren te laten liggen."]}
 ]},
 "waarom-staat-makreel-op-rood":{excerpt:"Good Fish wijzigde in april 2025 het advies voor Noordoost-Atlantische makreel. Herkomst en vangstmethode tellen mee bij het beoordelen van een specifiek product.",secties:[
 {alineas:["Een duurzaamheidsbeoordeling is geen oordeel over voedselveiligheid. Vraag ons naar de herkomst en vangstmethode van de aangeboden makreel."]},
 {kop:"Wat is er aan de hand?",alineas:["De waarschuwing van Good Fish uit april 2025 gaat over overbevissing en het ontbreken van gezamenlijke vangstafspraken.","Controleer de actuele VISwijzer voor de specifieke visserij in plaats van aan te nemen dat elke makreel dezelfde beoordeling heeft."]},
 {kop:"Wat betekent dat aan onze toonbank?",alineas:["Wij bieden makreel aan, maar presenteren deze niet automatisch als duurzaam.","Vraag naar certificering en alternatieven. Alleen een productnaam bewijst geen milieubeoordeling."]},
 {kop:"Uw keuze maken",alineas:["Gebruik de actuele viswijzer en bespreek de mogelijkheden met ons. Kies voor controleerbare certificering of herkomst in plaats van een algemene claim."]}
 ],gerelateerdeLinks:[{label:"Biologische vis en keurmerken",href:"/biologische-vis"},{label:"Good Fish: achtergrond van het makreeladvies",href:"https://www.goodfish.nl/nl/makreel-overbevist-en-vanaf-vandaag-in-het-rood-op-de-viswijzer/"}]},
 "wilde-zalm-vs-kweekzalm-waarom-wij-varlaks-kiezen":{gerelateerdeRecepten:["zalm-citroen-dille"]},
 "kibbeling-vs-lekkerbek-het-verschil":{secties:[
 {alineas:["Aan de toonbank krijgen we regelmatig de vraag wat het verschil is tussen kibbeling en lekkerbek. Hieronder leggen we uit wat u krijgt en hoe u een keuze maakt."]},
 {kop:"Kibbeling: stukjes",alineas:["Onze kibbeling maken we van pollak: stukjes vis in beslag, goudbruin gebakken. Lekker met ravigottesaus. Voor lekkerbek gebruiken we heek, geen pollak."]},
 {kop:"Lekkerbek: een hele filet van heek",alineas:["Onze lekkerbek is een heekfilet in beslag, goudbruin gebakken. U krijgt een hele filet in plaats van de kleine stukjes van kibbeling."]},
 {kop:"Welke kiest u?",alineas:["Kibbeling is makkelijk om te delen en past goed bij ravigottesaus. Lekkerbek is handig op een broodje of als onderdeel van een maaltijd. Voedingswaarden verschillen met de vis, het beslag en de portie; de gegevens bij onze producten zijn indicatief.","Komt u voor een grotere hoeveelheid op een drukke dag? Vraag vooraf via WhatsApp naar de mogelijkheden. Uw bericht is geen bevestigde bestelling of garantie dat iets klaarstaat."]}
 ]},
 "de-echte-hollandse-garnaal":{excerpt:"De Hollandse garnaal is klein en heeft een zoete, zilte smaak. Lees over het verschil met grote garnalen, verwerking en MSC-certificering.",secties:[
 {alineas:["De Hollandse garnaal, Crangon crangon, is niet dezelfde soort als een grote tropische gamba. Hij is klein en grijsbruin in het water en verandert van kleur door het koken. De zoete, zilte smaak past goed bij toast, een cocktail of een eenvoudige salade."]},
 {kop:"Van vangst tot uw bord",alineas:["Herkomst en verwerking horen bij de specifieke levering. Vraag ons naar de leverancier, het vangstgebied en de manier waarop de aangeboden garnalen zijn gepeld.","In recepten gebruiken we gepelde, al gekookte garnalen. Houd ze gekoeld en voeg ze kort voor het serveren toe; lang meekoken doet de structuur geen goed."]},
 {kop:"MSC-gecertificeerd",alineas:["Wij bieden MSC-gecertificeerde Hollandse garnalen aan. MSC gaat over duurzame wildvangst en traceerbaarheid; het is geen biologisch keurmerk. Controleer bij aankoop de informatie van het specifieke product.","Vraag via WhatsApp naar de actuele beschikbaarheid als u voor een bepaald gerecht of een grotere hoeveelheid komt. We bespreken graag wat mogelijk is."]}
 ]},
 "marktdag-in-leiden-achter-de-kraam":{secties:[
 {alineas:["De Leidse markt is al jaren ons tweede thuis. Elke woensdag en zaterdag bouwen we onze kraam op. Achter een broodje haring of een bakje kibbeling zit een ochtend vol voorbereiding."]},
 {kop:"Voor de eerste klanten",alineas:["Op marktdagen moet de vis worden geladen, het ijs klaargemaakt en de bakolie op temperatuur gebracht. Daarna richten we de toonbank in, zodat klanten hun vis kunnen kiezen en vragen kunnen stellen."]},
 {kop:"Waarom de markt anders is dan de winkel",alineas:["Op de markt gaat het sneller en directer. U ziet de vis, ruikt de gebakken kibbeling en hoort de gesprekken bij de kraam. Voor veel klanten hoort een bezoek bij de wekelijkse boodschappen.","Wilt u een visschaal bij de markt ophalen? Spreek locatie, datum en tijd vooraf met ons af en laat dit bevestigen. Een bericht betekent niet automatisch dat alles klaarstaat of dat u niet hoeft te wachten."]},
 {kop:"Drie plekken, één kwaliteit",alineas:["Onze winkel aan de Herenstraat is open van dinsdag tot en met zaterdag. Op woensdag en zaterdag staan we op de Leidse markt, op vrijdag bij Hoogvliet in Voorschoten. Bekijk de locaties voor de juiste tijden en route; het herkenningspunt van woensdag is niet hetzelfde als dat van zaterdag."]}
 ]}
};
