import { viskalenderData } from "./viskalender";
import { siteLanguage } from "./language";

// Full editorial translations; seasonal guidance is not a stock guarantee.
const TEXT = {
 en: [
  ["Winter cod, skrei and shellfish", "Skrei usually arrives from Norway between January and April. Cod suits warming oven dishes; mussels and oysters are good winter options too. Ask us what is available today.", "Cod with lemon butter sauce"],
  ["A good time for cod and scallops", "Choose a warming fish meal or scallops as a starter. The mussel season is not over in February: Zeeland bottom-cultured mussels are usually available from July to April.", "Scallops from our range"],
  ["From winter fish to fresh spring dishes", "You can often still find mussels in March. Dutch brown shrimp are not just a spring product: supplies are possible in other months too. A fresh shrimp salad or oysters suit the start of spring.", "Oysters with shallot vinegar"],
  ["Lighter cooking with fresh fish", "The usual season for Zeeland bottom-cultured mussels ends around April, although the exact end varies by harvest. Choose fresh fillets with spring vegetables or Dutch brown shrimp, and ask us about the best current supplies.", "Cod with samphire and fennel"],
  ["Fresh fillets with spring vegetables", "Light fish dishes suit May. The new herring catch comes later: the start of Hollandse Nieuwe is set each year. Salmon remains a versatile option beyond any single season.", "Pan-fried plaice fillet with herbs and lemon"],
  ["Looking forward to Hollandse Nieuwe", "Sales of Hollandse Nieuwe usually begin in June. The exact start date and supplies vary from year to year. Ask us when the new-season herring arrives; enjoy it with chopped onions or in a bread roll.", "Dutch herring with onions"],
  ["Summer herring and the new mussel harvest", "The Zeeland bottom-cultured mussel season usually starts in July, sometimes earlier, depending on weather, quality and supply. Herring and plaice are good choices for a summer meal too.", "Herring roll with onions"],
  ["Shrimp, herring and a pot of mussels", "A shrimp cocktail, herring bites or mussels on the table: August offers plenty of inspiration. Kibbeling is a year-round favourite, not only a seasonal fish dish. We make our kibbeling with pollack.", "Dutch brown shrimp cocktail"],
  ["Summer carries on in the mussel pot", "By September, the mussel season has usually been underway for some time, rather than just starting. Plaice and Dutch brown shrimp also suit the transition to autumn. Quality and availability still depend on current supplies.", "Pan-fried plaice with tomatoes and olives"],
  ["Warming oven dishes and fish stew", "Cod and whiting work well in an oven dish or stew. A pot of mussels also suits an autumn evening. The calendar offers inspiration, not a stock guarantee: ask us which fillets are best today.", "Oven-baked cod with tomatoes and olives"],
  ["Fish soup and festive menu ideas", "A steaming fish soup suits November. Mussels and oysters are often available; smoked salmon is a year-round product. Start thinking about your festive menu and discuss special wishes with us.", "Creamy fish soup with vegetables"],
  ["A festive table with fish", "Smoked salmon, shrimp and shellfish bring colour to a festive menu. Salmon and shrimp are not limited to December. Want a seafood platter for a larger group? Discuss the contents and your budget with us in good time.", "Smoked salmon rolls with cream cheese"],
 ],
 de: [
  ["Winterlicher Kabeljau, Skrei und Schalentiere", "Skrei kommt normalerweise zwischen Januar und April aus Norwegen. Kabeljau passt zu wärmenden Ofengerichten; Miesmuscheln und Austern sind auch im Winter eine schöne Wahl. Fragen Sie uns, was heute erhältlich ist.", "Kabeljau mit Zitronen-Buttersauce"],
  ["Eine gute Zeit für Kabeljau und Jakobsmuscheln", "Wählen Sie ein winterliches Fischgericht oder Jakobsmuscheln als Vorspeise. Die Muschelsaison ist im Februar noch nicht vorbei: Zeeland-Bodenmuscheln sind in der Regel von Juli bis April erhältlich.", "Jakobsmuscheln aus unserem Sortiment"],
  ["Vom Winterfisch zu frischen Frühlingsgerichten", "Im März sind häufig noch Miesmuscheln erhältlich. Nordseegarnelen sind nicht nur ein Frühlingsprodukt: Auch in anderen Monaten sind Lieferungen möglich. Ein frischer Garnelensalat oder Austern passen zum Frühling.", "Austern mit Schalottenessig"],
  ["Leichter kochen mit frischem Fisch", "Im April endet gewöhnlich die Saison der Zeeland-Bodenmuscheln. Das genaue Ende hängt von der Ernte ab. Wählen Sie frisches Filet mit Frühlingsgemüse oder Nordseegarnelen und fragen Sie nach dem aktuellen Angebot.", "Kabeljau mit Queller und Fenchel"],
  ["Frisches Filet mit Frühlingsgemüse", "Leichte Fischgerichte passen gut in den Mai. Der neue Heringsfang kommt später: Der Verkaufsstart der Hollandse Nieuwe wird jedes Jahr festgelegt. Lachs bleibt auch außerhalb einer bestimmten Saison vielseitig.", "Gebratenes Schollenfilet mit Kräutern und Zitrone"],
  ["Vorfreude auf Hollandse Nieuwe", "Der Verkauf der Hollandse Nieuwe beginnt gewöhnlich im Juni. Das genaue Startdatum und die Lieferungen variieren von Jahr zu Jahr. Fragen Sie uns, wann der neue Matjes da ist; lecker mit Zwiebeln oder im Brötchen.", "Niederländischer Matjes mit Zwiebeln"],
  ["Sommerlicher Matjes und die neue Muschelernte", "Die Saison der Zeeland-Bodenmuscheln beginnt normalerweise im Juli, manchmal früher. Das hängt von Wetter, Qualität und Angebot ab. Auch Matjes und Scholle passen zu einem sommerlichen Essen.", "Matjesbrötchen mit Zwiebeln"],
  ["Garnelen, Matjes und ein Topf Miesmuscheln", "Garnelencocktail, Matjeshäppchen oder Muscheln auf dem Tisch: Der August bietet viele Ideen. Kibbeling ist ganzjährig beliebt und nicht nur ein saisonales Fischgericht. Unsere Kibbeling machen wir aus Pollack.", "Nordseegarnelencocktail"],
  ["Der Sommer geht im Muscheltopf weiter", "Im September läuft die Muschelsaison gewöhnlich bereits und beginnt nicht erst. Auch Scholle und Nordseegarnelen passen zum Übergang in den Herbst. Qualität und Verfügbarkeit hängen weiterhin vom aktuellen Angebot ab.", "Gebratene Scholle mit Tomaten und Oliven"],
  ["Wärmende Ofengerichte und Fischeintopf", "Kabeljau und Wittling eignen sich für Ofengerichte oder Eintöpfe. Auch ein Topf Miesmuscheln passt zu einem Herbstabend. Der Kalender gibt Anregungen, keine Vorratsgarantie: Fragen Sie uns nach den heute schönsten Filets.", "Kabeljau aus dem Ofen mit Tomaten und Oliven"],
  ["Fischsuppe und Ideen für die Feiertage", "Eine dampfende Fischsuppe passt zum November. Miesmuscheln und Austern sind oft erhältlich; Räucherlachs gibt es ganzjährig. Planen Sie Ihr Festmenü frühzeitig und besprechen Sie besondere Wünsche mit uns.", "Cremige Fischsuppe mit Gemüse"],
  ["Ein festlicher Tisch mit Fisch", "Räucherlachs, Garnelen und Schalentiere bringen Farbe ins Festmenü. Lachs und Garnelen sind nicht auf Dezember beschränkt. Möchten Sie eine Fischplatte für eine größere Runde? Besprechen Sie Inhalt und Budget rechtzeitig mit uns.", "Räucherlachsröllchen mit Frischkäse"],
 ],
} as const;
const FISH:Record<string,readonly[string,string]>={Kabeljauw:["Cod","Kabeljau"],"Skrei (bij seizoensaanvoer)":["Skrei (subject to seasonal supply)","Skrei (bei saisonaler Lieferung)"],Skrei:["Skrei","Skrei"],Oesters:["Oysters","Austern"],Mosselen:["Mussels","Miesmuscheln"],Coquilles:["Scallops","Jakobsmuscheln"],"Hollandse garnalen":["Dutch brown shrimp","Nordseegarnelen"],Schol:["Plaice","Scholle"],Tong:["Sole","Seezunge"],Zalm:["Salmon","Lachs"],"Hollandse Nieuwe (vanaf de seizoensstart)":["Hollandse Nieuwe (from the season opening)","Hollandse Nieuwe (ab Saisonstart)"],Haring:["Herring","Matjes"],"Mosselen (nieuwe oogst)":["Mussels (new harvest)","Miesmuscheln (neue Ernte)"],Kibbeling:["Kibbeling","Kibbeling"],Wijting:["Whiting","Wittling"],"Gerookte zalm":["Smoked salmon","Räucherlachs"]};
export function localizedCalendar(locale:string){
 const lang=siteLanguage(locale);
 return viskalenderData.map((month,i)=>{
  if(lang==="nl")return month;
  const t=TEXT[lang][i];if(!t)throw new Error(`Missing calendar month ${i}`);
  const date=new Date(Date.UTC(2026,i,1));
  return {...month,naam:new Intl.DateTimeFormat(lang,{month:"long",timeZone:"UTC"}).format(date),afkorting:new Intl.DateTimeFormat(lang,{month:"short",timeZone:"UTC"}).format(date),seizoen:({Winter:["Winter","Winter"],Lente:["Spring","Frühling"],Zomer:["Summer","Sommer"],Herfst:["Autumn","Herbst"]} as const)[month.seizoen][lang==="en"?0:1],hoogtepunt:t[0],tekst:t[1],foto:{...month.foto,alt:t[2]},vis:month.vis.map(f=>{const n=FISH[f.naam];if(!n)throw new Error(`Missing calendar fish ${f.naam}`);return {...f,naam:n[lang==="en"?0:1]};}),links:month.links.map(l=>({href:l.href.replace(/^\/nl\//,`/${lang}/`),label:l.href.includes("visschalen")?(lang==="en"?"View seafood platters":"Fischplatten ansehen"):l.href.includes("recepten")?(lang==="en"?"Recipes to cook":"Passende Rezepte"):(lang==="en"?"More about this fish":"Mehr über diesen Fisch")}))};
 });
}
export const CALENDAR_COPY={
 nl:{name:"Viskalender",meta:"Viskalender: welke vis is in het seizoen? | Schaap’s Vis",description:"Welke vis is in het seizoen? Bekijk onze viskalender per maand met foto’s, kooktips en recepten. Vraag Schaap’s Vis in Leiden naar de actuele aanvoer.",label:"Seizoensvis · Leiden",title:"De viskalender — wat is nu op zijn best?",intro:"Welke vis past bij deze maand? Ontdek seizoensaanvoer, kookideeën en recepten. De kalender helpt u kiezen; wat vandaag verkrijgbaar is, hangt af van de vangst en levering.",range:"Het assortiment",mussels:"Mosselen",musselSeason:"Doorgaans juli–april",herring:"Hollandse Nieuwe",herringSeason:"Seizoensstart meestal in juni",supply:"Aanvoer",ask:"Vraag wat vandaag verkrijgbaar is",thisMonth:"Deze maand",at:"bij Schaap’s",availability:"Dit zijn seizoensideeën, geen voorraadgarantie. Vraag ons naar de vis die vandaag verkrijgbaar is.",allAbout:"Meer over",months:"Maanden",now:"Ideeën voor deze maand",what:"Vis om naar te vragen",faq:"Vragen over seizoensvis",source:"Seizoensbron",disclaimer:"Dit zijn algemene indicaties, geen garanties voor onze dagvoorraad.",slot:"Weten wanneer het binnen is?",slotText:"Vraag ons via WhatsApp wat er vandaag verkrijgbaar is. We denken graag mee over de vis, porties en een passend recept.",platter:"Visschaal samenstellen",questions:[{v:"Wanneer is het mosselseizoen?",a:"Zeeuwse bodemcultuurmosselen zijn doorgaans van juli tot april verkrijgbaar. De start en het einde kunnen per oogst verschillen. Hangcultuurmosselen kunnen eerder beschikbaar zijn. Vraag ons naar de actuele aanvoer."},{v:"Wanneer komt de Hollandse Nieuwe?",a:"Het nieuwe haringseizoen begint doorgaans in juni. De exacte verkoopstart wordt ieder jaar vastgesteld; vraag ons wanneer de nieuwe haring er is."},{v:"Is zalm alleen in een bepaald seizoen verkrijgbaar?",a:"Kweekzalm en gerookte zalm zijn doorgaans jaarrond verkrijgbaar. De viskalender helpt bij gerechten en seizoensaanvoer, maar is geen voorraadgarantie."},{v:"Kan ik de vis uit de kalender bestellen?",a:"Voor visproducten kunt u via WhatsApp vragen naar de beschikbaarheid en mogelijkheden. Alleen visschalen kunt u online samenstellen en bestellen."}]},
 en:{name:"Fish calendar",meta:"Fish calendar: which fish is in season? | Schaap’s Vis",description:"Explore our monthly fish calendar with photos, cooking ideas and recipes. Ask Schaap’s Vishandel in Leiden about current supplies.",label:"Seasonal fish · Leiden",title:"The fish calendar — what suits the season?",intro:"Which fish suits this month? Explore seasonal supplies, cooking ideas and recipes. The calendar helps you choose; what is available today depends on catches and deliveries.",range:"Our fish range",mussels:"Mussels",musselSeason:"Usually July–April",herring:"Hollandse Nieuwe",herringSeason:"Season usually opens in June",supply:"Supply",ask:"Ask what is available today",thisMonth:"This month",at:"at Schaap’s",availability:"These are seasonal ideas, not a stock guarantee. Ask us which fish is available today.",allAbout:"More about",months:"Months",now:"Ideas for this month",what:"Fish to ask about",faq:"Questions about seasonal fish",source:"Seasonal source",disclaimer:"These are general indications, not guarantees of our daily stock.",slot:"Want to know when it arrives?",slotText:"Ask us on WhatsApp what is available today. We can help you choose fish, portions and a suitable recipe.",platter:"Build a seafood platter",questions:[{v:"When is mussel season?",a:"Zeeland bottom-cultured mussels are usually available from July to April. The beginning and end vary by harvest. Rope-grown mussels may be available earlier. Ask us about current supplies."},{v:"When does Hollandse Nieuwe arrive?",a:"The new herring season usually begins in June. The exact sales opening is set each year; ask us when the new-season herring arrives."},{v:"Is salmon only available in a particular season?",a:"Farmed salmon and smoked salmon are usually available year-round. The fish calendar helps with meals and seasonal supplies, but does not guarantee stock."},{v:"Can I order fish from the calendar?",a:"For fish products, ask us on WhatsApp about availability and options. Only seafood platters can be assembled and ordered online."}]},
 de:{name:"Fischkalender",meta:"Fischkalender: Welcher Fisch hat Saison? | Schaap’s Vis",description:"Entdecken Sie unseren monatlichen Fischkalender mit Fotos, Kochideen und Rezepten. Fragen Sie Schaap’s Vishandel in Leiden nach dem aktuellen Angebot.",label:"Saisonaler Fisch · Leiden",title:"Der Fischkalender — was passt zur Saison?",intro:"Welcher Fisch passt zu diesem Monat? Entdecken Sie saisonale Lieferungen, Kochideen und Rezepte. Der Kalender hilft bei der Auswahl; das heutige Angebot hängt von Fang und Lieferung ab.",range:"Unser Sortiment",mussels:"Miesmuscheln",musselSeason:"Gewöhnlich Juli–April",herring:"Hollandse Nieuwe",herringSeason:"Saisonstart meistens im Juni",supply:"Angebot",ask:"Fragen Sie, was heute erhältlich ist",thisMonth:"Diesen Monat",at:"bei Schaap’s",availability:"Dies sind saisonale Ideen, keine Vorratsgarantie. Fragen Sie uns, welcher Fisch heute erhältlich ist.",allAbout:"Mehr zum",months:"Monate",now:"Ideen für diesen Monat",what:"Fisch, nach dem Sie fragen können",faq:"Fragen zu saisonalem Fisch",source:"Saisonquelle",disclaimer:"Dies sind allgemeine Hinweise, keine Garantien für unseren Tagesvorrat.",slot:"Möchten Sie wissen, wann er da ist?",slotText:"Fragen Sie per WhatsApp, was heute erhältlich ist. Wir beraten Sie gern zu Fisch, Portionsgrößen und passenden Rezepten.",platter:"Fischplatte zusammenstellen",questions:[{v:"Wann ist Muschelsaison?",a:"Zeeland-Bodenmuscheln sind gewöhnlich von Juli bis April erhältlich. Beginn und Ende hängen von der Ernte ab. Hängekulturmuscheln können früher erhältlich sein. Fragen Sie nach dem aktuellen Angebot."},{v:"Wann kommt die Hollandse Nieuwe?",a:"Die neue Matjessaison beginnt gewöhnlich im Juni. Der genaue Verkaufsstart wird jährlich festgelegt; fragen Sie uns, wann der neue Matjes da ist."},{v:"Ist Lachs nur in einer bestimmten Saison erhältlich?",a:"Zuchtlachs und Räucherlachs sind gewöhnlich ganzjährig erhältlich. Der Fischkalender hilft bei Gerichten und saisonalem Angebot, garantiert aber keinen Vorrat."},{v:"Kann ich den Fisch aus dem Kalender bestellen?",a:"Fragen Sie bei Fischprodukten per WhatsApp nach Verfügbarkeit und Möglichkeiten. Nur Fischplatten können online zusammengestellt und bestellt werden."}]},
};
export function calendarCopy(locale:string){return CALENDAR_COPY[siteLanguage(locale)];}
