import { siteLanguage } from "./language";

const COPY = {
  nl: {
    range:"Assortiment", browse:"Bekijk het assortiment", platter:"Visschaal samenstellen", available:"Beschikbaar", daily:"Dagelijks vers", seasonal:"Seizoensgebonden", request:"Op aanvraag", price:"Prijs", guidePrice:"richtprijs", dailyPrice:"Op aanvraag, dagprijs", best:"Op zijn best",
    availabilityNote:"Dit ligt niet elke dag in de vitrine. Vraag ons naar de beschikbaarheid op uw ophaaldatum via WhatsApp of telefoon.", alternative:"Onze VÅRLAKS-zalm", salmon:"Meer over VÅRLAKS-zalm →", salmonNote:"Lees over de kwekers en herkomst. Vraag naar de certificering van de actuele levering.", inspiration:"Inspiratie", cooking:"Wat maakt u ermee?", ideas:"Bereiding, bewaartips en recepten voor uw vis.", blog:"Uit onze blog", recipes:"Recepten bekijken", recipesNote:"Ontdek gerechten met vis en tips voor de bereiding.", ingredients:"Ingrediënten en allergenen", contains:"Bevat", allergenNote:"Samenstelling en allergenen kunnen per product en levering verschillen. Controleer altijd het actuele etiket en bespreek een allergie met ons vóór aankoop.", season:"Wanneer het lekkerst is", nutrition:"Voedingswaarde", per100:"Gemiddeld per 100 gram", energy:"Energie", fat:"Vetten", saturated:"waarvan verzadigd", carbs:"Koolhydraten", sugars:"waarvan suikers", protein:"Eiwitten", salt:"Zout", nutritionNote:"Indicatieve gemiddelden; de werkelijke waarden verschillen per vangst, seizoen en bereiding.", nutritionRequest:"Vraag aan de toonbank naar de voedingswaarde.", priceNote:"Dit is een richtprijs. De dagprijs en uiteindelijke prijs op gewicht bevestigen we voordat u beslist.", back:"Terug naar het assortiment", looking:"Op zoek naar", orderNote:"Alleen visschalen kunt u online bestellen. Zoekt u iets anders? Stuur ons een WhatsApp-bericht, dan kijken we samen wat mogelijk is.", hours:"Openingstijden en route", dutch:"Nederlands", meta:"Bekijk productinformatie, ingrediënten en allergenen bij Schaap’s Vishandel in Leiden. Vraag via WhatsApp naar de actuele beschikbaarheid.",
  },
  en: {
    range:"Fish range", browse:"Explore our fish range", platter:"Create a seafood platter", available:"Availability", daily:"Fresh daily", seasonal:"Seasonal", request:"On request", price:"Price", guidePrice:"guide price", dailyPrice:"Ask for today’s price", best:"Best season",
    availabilityNote:"This is not in our counter every day. Ask about availability on your collection date via WhatsApp or phone.", alternative:"Our VÅRLAKS salmon", salmon:"More about VÅRLAKS salmon →", salmonNote:"Read about the farmers and origin. Ask about the certification of the current delivery.", inspiration:"Inspiration", cooking:"What can you make with it?", ideas:"Cooking ideas, storage tips and recipes for your fish.", blog:"From our blog", recipes:"Explore fish recipes", recipesNote:"Discover fish dishes and preparation tips.", ingredients:"Ingredients and allergens", contains:"Contains", allergenNote:"Ingredients and allergens may vary by product and delivery. Always check the current label and discuss any allergy with us before buying.", season:"When it tastes its best", nutrition:"Nutritional information", per100:"Average per 100 grams", energy:"Energy", fat:"Fat", saturated:"of which saturates", carbs:"Carbohydrate", sugars:"of which sugars", protein:"Protein", salt:"Salt", nutritionNote:"Indicative averages; actual values vary with the catch, season and preparation.", nutritionRequest:"Ask at our counter for nutritional information.", priceNote:"This is a guide price. We confirm today’s price and the final price by weight before you decide.", back:"Back to our fish range", looking:"Looking for", orderNote:"Only seafood platters can be ordered online. Looking for something else? Send us a WhatsApp message and we will discuss what is possible.", hours:"Opening hours and directions", dutch:"Dutch", meta:"Explore product information, ingredients and allergens at Schaap’s fishmonger in Leiden. Ask us on WhatsApp about current availability.",
  },
  de: {
    range:"Fischsortiment", browse:"Unser Fischsortiment ansehen", platter:"Fischplatte zusammenstellen", available:"Verfügbarkeit", daily:"Täglich frisch", seasonal:"Saisonal", request:"Auf Anfrage", price:"Preis", guidePrice:"Richtpreis", dailyPrice:"Tagespreis auf Anfrage", best:"Beste Saison",
    availabilityNote:"Dieses Produkt liegt nicht täglich in unserer Theke. Fragen Sie per WhatsApp oder telefonisch nach der Verfügbarkeit an Ihrem Abholtag.", alternative:"Unser VÅRLAKS-Lachs", salmon:"Mehr über VÅRLAKS-Lachs →", salmonNote:"Erfahren Sie mehr über Züchter und Herkunft. Fragen Sie nach der Zertifizierung der aktuellen Lieferung.", inspiration:"Inspiration", cooking:"Was können Sie damit zubereiten?", ideas:"Zubereitungsideen, Aufbewahrungstipps und Rezepte für Ihren Fisch.", blog:"Aus unserem Blog", recipes:"Fischrezepte entdecken", recipesNote:"Entdecken Sie Fischgerichte und Tipps zur Zubereitung.", ingredients:"Zutaten und Allergene", contains:"Enthält", allergenNote:"Zutaten und Allergene können je nach Produkt und Lieferung variieren. Prüfen Sie stets das aktuelle Etikett und besprechen Sie Allergien vor dem Kauf mit uns.", season:"Wann er am besten schmeckt", nutrition:"Nährwerte", per100:"Durchschnittlich pro 100 Gramm", energy:"Energie", fat:"Fett", saturated:"davon gesättigte Fettsäuren", carbs:"Kohlenhydrate", sugars:"davon Zucker", protein:"Eiweiß", salt:"Salz", nutritionNote:"Ungefähre Durchschnittswerte; tatsächliche Werte variieren je nach Fang, Saison und Zubereitung.", nutritionRequest:"Fragen Sie an unserer Theke nach den Nährwerten.", priceNote:"Dies ist ein Richtpreis. Tagespreis und endgültigen Preis nach Gewicht bestätigen wir, bevor Sie sich entscheiden.", back:"Zurück zum Fischsortiment", looking:"Sie suchen", orderNote:"Nur Fischplatten können online bestellt werden. Suchen Sie etwas anderes? Schreiben Sie uns per WhatsApp; wir besprechen gerne, was möglich ist.", hours:"Öffnungszeiten und Anfahrt", dutch:"Niederländisch", meta:"Produktinformationen, Zutaten und Allergene bei Schaap’s Fischhandel in Leiden. Fragen Sie uns per WhatsApp nach der aktuellen Verfügbarkeit.",
  },
};
export const productCopy = (locale: string) => COPY[siteLanguage(locale)];

// Exact whole-sentence translations, not word replacement.
const NOTES: Record<string, readonly [string, string]> = {
  "Koud water maakt kabeljauw in de winter extra stevig en sneeuwwit.": ["Cold winter water gives cod particularly firm, white flesh.", "Kaltes Winterwasser sorgt bei Kabeljau für besonders festes, weißes Fleisch."],
  "Schol is op zijn best van mei tot augustus, wanneer hij goed op vlees is.": ["Plaice is at its best from May to August, when the flesh is well developed.", "Scholle schmeckt von Mai bis August besonders gut, wenn sie gut genährt ist."],
  "Op zijn best als Hollandse Nieuwe, van half juni tot eind augustus.": ["Best as new-season Dutch herring, from mid-June to late August.", "Als Hollandse Nieuwe von Mitte Juni bis Ende August besonders lecker."],
  "Vers vanaf het vroege voorjaar; hoogseizoen in de nazomer en herfst.": ["Available fresh from early spring; peak season is late summer and autumn.", "Frisch ab dem frühen Frühjahr; Hauptsaison im Spätsommer und Herbst."],
  "Mosselseizoen loopt van juli tot april — het vlezigst in oktober en november.": ["Mussel season runs from July to April, with the fullest meat in October and November.", "Muschelsaison ist von Juli bis April; besonders fleischig im Oktober und November."],
  "Oesters zijn op hun best in de koude maanden, van september tot april.": ["Oysters are at their best in the colder months, September to April.", "Austern schmecken in den kühleren Monaten von September bis April besonders gut."],
  "Kokkels zijn het lekkerst in de koelere maanden.": ["Cockles taste best in the cooler months.", "Herzmuscheln schmecken in den kühleren Monaten am besten."],
  "Coquilles zijn op hun mooist in de herfst en winter.": ["Scallops are at their best in autumn and winter.", "Jakobsmuscheln sind im Herbst und Winter besonders gut."],
  "Het lekkerst tijdens het Hollandse Nieuwe-seizoen (half juni–augustus).": ["Best during the Dutch new-herring season, mid-June to August.", "Besonders lecker während der Hollandse-Nieuwe-Saison von Mitte Juni bis August."],
  "In de wintermaanden is kabeljauw op zijn allerbest.": ["Cod is at its best during the winter months.", "Kabeljau ist in den Wintermonaten besonders gut."],
  "Tongschar is op zijn best in de koudere maanden.": ["Lemon sole is at its best in the colder months.", "Rotzunge ist in den kälteren Monaten besonders gut."],
  "Sardines zijn op hun vetst en lekkerst in de zomermaanden.": ["Sardines are richest and tastiest in the summer months.", "Sardinen sind im Sommer besonders fettreich und aromatisch."],
  "Verse ansjovis is een zomerse vangst.": ["Fresh anchovies are a summer catch.", "Frische Sardellen sind ein Sommerfang."],
  "Skrei is dé winterdelicatesse — verkrijgbaar van januari tot april.": ["Skrei is a winter delicacy, available January to April.", "Skrei ist eine Winterdelikatesse, von Januar bis April erhältlich."],
  "MSC-gecertificeerd. Vraag naar het actuele VISwijzer-advies en de levering.": ["MSC-certified. Ask us about the current fish guide and delivery.", "MSC-zertifiziert. Fragen Sie nach dem aktuellen Fischratgeber und der Lieferung."],
  "MSC-gecertificeerd — verantwoord gevangen.": ["MSC-certified, responsibly caught.", "MSC-zertifiziert, verantwortungsvoll gefangen."],
  "Vraag naar de actuele herkomst en productcertificering. BIO en ASC zijn verschillende aanduidingen.": ["Ask about current origin and product certification. Organic and ASC are different labels.", "Fragen Sie nach aktueller Herkunft und Produktzertifizierung. Bio und ASC sind unterschiedliche Kennzeichnungen."],
  "Vraag naar de herkomst en het keurmerk van de actuele levering.": ["Ask about the origin and certification of the current delivery.", "Fragen Sie nach Herkunft und Siegel der aktuellen Lieferung."],
  "Het VISwijzer-advies voor geelvintonijn hangt af van herkomst en vangstmethode. Vraag ons naar het actuele advies.": ["Fish-guide advice for yellowfin tuna depends on origin and fishing method. Ask us about the current advice.", "Die Empfehlung für Gelbflossenthun hängt von Herkunft und Fangmethode ab. Fragen Sie nach dem aktuellen Rat."],
  "ASC-gecertificeerd — verantwoorde kweek.": ["ASC-certified, responsibly farmed.", "ASC-zertifiziert, verantwortungsvoll gezüchtet."],
  "MSC-gecertificeerd sinds 2017 — verantwoord gevangen aan de Waddenkust.": ["MSC-certified since 2017, responsibly caught along the Wadden coast.", "Seit 2017 MSC-zertifiziert, verantwortungsvoll an der Wattenküste gefangen."],
  "Zwaardvis: let op de VISwijzer-status. Vraag ons naar het actuele advies.": ["Swordfish: check the fish-guide status. Ask us for current advice.", "Schwertfisch: Beachten Sie die Einstufung im Fischratgeber. Fragen Sie nach dem aktuellen Rat."],
};
export function productNote(value: string | undefined, locale: string): string | undefined {
  if (!value) return undefined;
  const lang = siteLanguage(locale);
  if (lang === "nl") return value;
  if (!NOTES[value]) throw new Error(`Missing product note translation: ${value}`);
  return NOTES[value][lang === "en" ? 0 : 1];
}
