import { siteLanguage } from "./language";

// Owner-confirmed stock information, not a live inventory feed.
// Each entry translates both the stock label and location/request instructions.
type StockCopy = readonly [string, string, string, string, string, string];
const STOCK: Record<string, StockCopy> = {
  always: ["Altijd op voorraad", "Voor grotere hoeveelheden kunt u vooraf contact opnemen.", "Always in stock", "Contact us in advance for larger quantities.", "Immer vorrätig", "Bei größeren Mengen kontaktieren Sie uns bitte vorab."],
  usually: ["Bijna altijd op voorraad", "Vraag vooraf naar de voorraad als u speciaal voor dit product komt.", "Almost always in stock", "Check stock beforehand if you are visiting specifically for this product.", "Fast immer vorrätig", "Fragen Sie vorher nach dem Bestand, wenn Sie eigens für dieses Produkt kommen."],
  sometimes: ["Soms op voorraad", "Niet standaard op voorraad. App ons om te vragen of het beschikbaar is.", "Sometimes in stock", "Not routinely in stock. Message us to check availability.", "Manchmal vorrätig", "Nicht ständig vorrätig. Fragen Sie per WhatsApp nach der Verfügbarkeit."],
  request: ["Alleen op aanvraag", "Stuur ons op tijd een WhatsApp-bericht met uw wensen, ophaaldatum en locatie. We bevestigen wat mogelijk is.", "On request only", "Message us in good time with your wishes, collection date and location. We will confirm what is possible.", "Nur auf Anfrage", "Schreiben Sie uns rechtzeitig mit Ihren Wünschen, Abholdatum und Standort. Wir bestätigen, was möglich ist."],
  "shop-always": ["Altijd in de viswinkel", "Dorade is altijd op voorraad in onze viswinkel in Leiden. Naar de markt of Hoogvliet? Bericht ons vooraf over de voorraad en uw gewenste ophaallocatie.", "Always in our fish shop", "Dorade is always in stock in our Leiden fish shop. Visiting the market or Hoogvliet? Message us beforehand about stock and your collection location.", "Immer im Fischgeschäft", "Dorade ist in unserem Fischgeschäft in Leiden immer vorrätig. Für den Markt oder Hoogvliet fragen Sie vorher nach Bestand und Abholort."],
  "shop-often": ["Vaak in de viswinkel", "Vaak op voorraad in onze winkel in Leiden. Vraag naar de actuele voorraad en vermeld waar u wilt ophalen.", "Often in our fish shop", "Often in stock in our Leiden shop. Check current stock and tell us where you would like to collect.", "Oft im Fischgeschäft", "Oft in unserem Geschäft in Leiden vorrätig. Fragen Sie nach dem Bestand und nennen Sie Ihren Abholort."],
  "shop-sometimes-or-request": ["Soms in de winkel, anders op aanvraag", "Kokkels zijn soms op voorraad in de viswinkel. Anders vragen we ze voor u aan; neem op tijd contact op.", "Sometimes in the shop; otherwise on request", "Cockles are sometimes in stock in our fish shop. Otherwise we can request them for you; contact us in good time.", "Manchmal im Geschäft, sonst auf Anfrage", "Herzmuscheln sind manchmal im Fischgeschäft vorrätig. Sonst fragen wir sie für Sie an; melden Sie sich rechtzeitig."],
  "shop-often-cart-request": ["Vaak in de winkel; viskar op aanvraag", "Hele zeebaars is vaak in de viswinkel en soms bij de viskar. Laat op tijd weten dat u hem op de markt of bij Hoogvliet wilt ophalen, dan bespreken we of we hem kunnen meenemen.", "Often in the shop; request for the fish stall", "Whole sea bass is often in our shop and sometimes at the fish stall. Let us know in good time if you want to collect at the market or Hoogvliet so we can discuss bringing it along.", "Oft im Geschäft; Verkaufswagen auf Anfrage", "Ganzer Wolfsbarsch ist oft im Geschäft und manchmal am Verkaufswagen erhältlich. Für den Markt oder Hoogvliet melden Sie sich rechtzeitig, damit wir das Mitbringen absprechen können."],
  "shop-and-cart-usually": ["Bijna altijd in winkel en viskar", "Zeebaarsfilet is bijna altijd op voorraad in onze viswinkel en viskar. Vraag vooraf als u voor een bepaalde hoeveelheid komt.", "Almost always in the shop and fish stall", "Sea bass fillet is almost always in stock in our shop and fish stall. Ask ahead if you need a particular quantity.", "Fast immer im Geschäft und Verkaufswagen", "Wolfsbarschfilet ist fast immer im Geschäft und am Verkaufswagen vorrätig. Fragen Sie bei bestimmten Mengen vorab nach."],
  quality: ["Beschikbaar bij goede kwaliteit", "We hebben gerookte wilde zalm op voorraad wanneer we goede kwaliteit kunnen verkrijgen. Vraag naar de actuele beschikbaarheid.", "Available when good quality can be sourced", "We stock smoked wild salmon when we can obtain good quality. Ask about current availability.", "Erhältlich bei guter Qualität", "Wir führen geräucherten Wildlachs, wenn wir gute Qualität beziehen können. Fragen Sie nach der aktuellen Verfügbarkeit."],
  "smokehouse-quality": ["Afhankelijk van de rokerij; aanvraag mogelijk", "We hebben gravad lax wanneer de rokerij goede kwaliteit kan leveren. Neem contact op om beschikbaarheid en een eventuele aanvraag te bespreken.", "Depends on the smokehouse; requests possible", "We stock gravlax when the smokehouse can supply good quality. Contact us about availability and a possible request.", "Abhängig von der Räucherei; Anfrage möglich", "Wir führen Graved Lachs, wenn die Räucherei gute Qualität liefern kann. Kontaktieren Sie uns zur Verfügbarkeit und einer möglichen Anfrage."],
  "live-request": ["Levende kreeft, uitsluitend op aanvraag", "Een levende kreeft nemen we alleen op aanvraag mee. Zo voorkomen we dat een levend dier onverkocht blijft. Geef uw wensen op tijd door; levering bevestigen we persoonlijk.", "Live lobster, on request only", "We obtain live lobster only on request to avoid a live animal remaining unsold. Tell us your wishes in good time; we confirm supply personally.", "Lebender Hummer, nur auf Anfrage", "Lebenden Hummer besorgen wir nur auf Anfrage, damit kein lebendes Tier unverkauft bleibt. Teilen Sie uns Ihre Wünsche rechtzeitig mit; wir bestätigen die Lieferung persönlich."],
  "shop-only": ["In de viswinkel", "Vissoep is verkrijgbaar in onze viswinkel in Leiden. Nodig op de markt of bij Hoogvliet? Geef dit op tijd door zodat we de mogelijkheden kunnen bespreken.", "In our fish shop", "Fish soup is available in our Leiden shop. Need it at the market or Hoogvliet? Let us know in good time so we can discuss the options.", "Im Fischgeschäft", "Fischsuppe erhalten Sie in unserem Geschäft in Leiden. Für den Markt oder Hoogvliet teilen Sie uns Ihren Wunsch rechtzeitig mit."],
  "rare-request": ["Bijna nooit op voorraad; op aanvraag", "Verse sardines zijn bijna nooit standaard op voorraad. Vraag op tijd of we ze voor u kunnen meenemen.", "Rarely stocked; on request", "Fresh sardines are rarely routinely in stock. Ask in good time whether we can obtain them for you.", "Selten vorrätig; auf Anfrage", "Frische Sardinen sind fast nie regulär vorrätig. Fragen Sie rechtzeitig, ob wir sie für Sie besorgen können."],
  "sometimes-request": ["Soms op voorraad; app vooraf", "Hele wijting is soms op voorraad, maar vaak is vooraf een WhatsApp-bericht nodig. Wijtingfilet is uitsluitend op aanvraag. Onze lekkerbek maken we van heek.", "Sometimes in stock; message ahead", "Whole whiting is sometimes in stock, but often requires a WhatsApp message beforehand. Whiting fillet is on request only. Our lekkerbek is made from hake.", "Manchmal vorrätig; vorher schreiben", "Ganzer Wittling ist manchmal vorrätig, oft ist eine vorherige WhatsApp-Nachricht nötig. Wittlingfilet gibt es nur auf Anfrage. Unser Lekkerbek wird aus Seehecht gemacht."],
  "request-bunch": ["Een bosje op aanvraag", "Scheermessen liggen niet standaard op voorraad. Op aanvraag kunnen we vaak een bosje meenemen; vraag dit vooraf en laat de beschikbaarheid bevestigen.", "A bunch on request", "Razor clams are not routinely stocked. We can often bring a bunch on request; ask beforehand and have availability confirmed.", "Ein Bündel auf Anfrage", "Schwertmuscheln sind nicht regulär vorrätig. Auf Anfrage können wir oft ein Bündel mitbringen; lassen Sie sich die Verfügbarkeit vorher bestätigen."],
  "oyster-choice": ["Vaak Fine de Claire of creuse", "We hebben vaak Fine de Claire of creuse oesters. Wilt u specifiek Fine de Claire? Vraag vooraf welke variant er is; creuse oesters zijn altijd op voorraad.", "Often Fine de Claire or cupped oysters", "We often have Fine de Claire or cupped oysters. Specifically want Fine de Claire? Check which variety is available; cupped oysters are always in stock.", "Oft Fine de Claire oder Felsenaustern", "Wir haben oft Fine-de-Claire- oder Felsenaustern. Für Fine de Claire fragen Sie vorher nach der Sorte; Felsenaustern sind immer vorrätig."],
  unavailable: ["Momenteel niet beschikbaar", "Dit product is niet meer op voorraad. Vraag ons naar een alternatief; dit is geen aanbod om het direct te bestellen.", "Currently unavailable", "This product is no longer in stock. Ask us about an alternative; it is not available for immediate ordering.", "Derzeit nicht verfügbar", "Dieses Produkt ist nicht mehr vorrätig. Fragen Sie nach einer Alternative; es kann nicht direkt bestellt werden."],
  current: ["Vraag naar de actuele voorraad", "Vraag ons naar de voorraad op uw gewenste datum en ophaallocatie.", "Ask about current stock", "Ask us about stock on your preferred date and at your collection location.", "Aktuellen Bestand erfragen", "Fragen Sie nach dem Bestand für Ihren gewünschten Tag und Abholort."],
  dagelijks: ["Dagelijks in ons assortiment", "Vraag bij een specifiek product of een grotere hoeveelheid naar de actuele voorraad.", "In our everyday range", "Check current stock for a particular product or a larger quantity.", "Im täglichen Sortiment", "Fragen Sie bei einem bestimmten Produkt oder größeren Mengen nach dem aktuellen Bestand."],
  seizoensgebonden: ["Seizoensgebonden", "Vraag naar de actuele aanvoer en voorraad.", "Seasonal", "Ask about current supply and stock.", "Saisonal", "Fragen Sie nach aktuellem Angebot und Bestand."],
};
export function productAvailability(product: {beschikbaar?: string}, locale: string) {
  const lang=siteLanguage(locale), key=product.beschikbaar==="op bestelling"?"request":product.beschikbaar??"current";
  const copy=STOCK[key];
  if(!copy)throw new Error(`Unknown product availability: ${key}`);
  const index=lang==="nl"?0:lang==="en"?2:4;
  return {label:copy[index],note:copy[index+1],unavailable:key==="unavailable"};
}
