import type { Recept } from "./recepten";

// Praktische, doenbare recepten — max 45 min, max 8 stappen,
// ingrediënten uit de viswinkel + gewone supermarkt.
export const receptenPraktisch: Recept[] = [
  // ── SNEL DOORDEWEEKS ──────────────────────────────────────────────
  {
    slug: "pasta-gerookte-zalm-roomsaus",
    title: "Pasta met gerookte zalm en roomsaus",
    subtitle: "Romige pasta in 20 minuten — de favoriet van elk gezin",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Romige tagliatelle met gerookte zalm en dille",
    vanSchaap: ["Gerookte zalm (200 g) — vraag naar de dikgesneden variant"],
    vanSupermarkt: [
      "400 g tagliatelle of penne",
      "250 ml kookroom",
      "1 sjalot + 2 tenen knoflook",
      "Verse dille of bieslook",
      "1 citroen",
      "Parmezaanse kaas",
      "Olijfolie",
    ],
    bereidingswijze: [
      "Kook de pasta volgens de verpakking beetgaar.",
      "Fruit intussen de gesnipperde sjalot en knoflook 2 minuten in olijfolie op middelhoog vuur.",
      "Voeg de kookroom toe en laat 3–4 minuten zachtjes inkoken. Breng op smaak met peper en een kneep citroen.",
      "Scheur de gerookte zalm in stukken.",
      "Schep de pasta met een lepel kookvocht door de saus, haal de pan van het vuur en voeg de zalm toe — niet meekoken, dan blijft hij zacht.",
      "Serveer met dille en Parmezaan.",
    ],
    verhaal:
      "Voeg de zalm pas op het laatst toe, van het vuur af — zo blijft de rooksmaak intact. Onze zalm wordt ambachtelijk gerookt; vraag naar de dikgesneden variant voor dit gerecht.",
    seoKeywords: "pasta gerookte zalm recept, romige zalmpasta, snelle zalmpasta",
  },
  {
    slug: "gebakken-kabeljauw-botersaus",
    title: "Gebakken kabeljauw met citroen-botersaus",
    subtitle: "Restaurantwaardig, maar klaar in 20 minuten",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk"],
    porties: 4,
    seizoen: "Jaarrond — op z'n best januari t/m maart",
    fotoLabel: "Gebakken kabeljauwfilet met botersaus en citroen",
    vanSchaap: ["4 kabeljauwfilets (à 150 g)"],
    vanSupermarkt: [
      "Bloem",
      "75 g roomboter",
      "1 citroen",
      "Verse peterselie",
      "Kappertjes (optioneel)",
      "Krieltjes en haricots verts als bijgerecht",
    ],
    bereidingswijze: [
      "Dep de kabeljauw droog en bestrooi met zout en peper.",
      "Haal de filets licht door de bloem en klop het overtollige eraf.",
      "Verhit een klont boter in een koekenpan op middelhoog vuur tot het schuim wegtrekt.",
      "Bak de kabeljauw 3–4 minuten op de eerste kant zonder te bewegen, keer voorzichtig en bak nog 2–3 minuten. Haal uit de pan.",
      "Voeg de rest van de boter toe en laat lichtbruin worden, roer dan citroensap, kappertjes en peterselie erdoor.",
      "Schep de saus over de vis en serveer met krieltjes.",
    ],
    verhaal:
      "Kabeljauw is gaar zodra hij in stevige witte vlokken uiteenvalt. Beweeg de vis niet tijdens het bakken — dan blijft hij heel.",
    seoKeywords: "kabeljauw bakken recept, gebakken kabeljauw botersaus, kabeljauwfilet pan",
  },
  {
    slug: "gebakken-wijting-citroen",
    title: "Gebakken wijting met citroen en peterselie",
    subtitle: "De ondergewaardeerde Noordzeevis — fijn van smaak, klaar in 15 minuten",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Op z'n best september t/m maart",
    fotoLabel: "Gebakken wijtingfilet met citroen",
    vanSchaap: ["4 wijtingfilets (à 125–150 g) — vraag ons ze graatvrij te maken"],
    vanSupermarkt: [
      "Bloem",
      "Boter of olijfolie",
      "1 citroen",
      "Verse peterselie",
      "Sperziebonen en aardappelen als bijgerecht",
    ],
    bereidingswijze: [
      "Dep de wijting droog, bestrooi met zout en peper en haal door de bloem.",
      "Verhit boter in een ruime koekenpan op middelhoog vuur.",
      "Bak de filets 2–3 minuten per kant goudbruin — wijting is dun, dus snel gaar.",
      "Bestrooi met peterselie en serveer direct met citroen.",
      "Lekker met gekookte aardappelen en sperziebonen.",
    ],
    verhaal:
      "Wijting is familie van de kabeljauw maar een stuk voordeliger — een echte vergeten Noordzeevis die meer aandacht verdient.",
    seoKeywords: "wijting recept, wijting bakken, wijtingfilet pan recept",
  },
  {
    slug: "tonijnsteak-grillen-sesam",
    title: "Gegrilde tonijnsteak met sesam en sojadip",
    subtitle: "Kort en krachtig grillen — van binnen mooi rosé",
    tijd: "15 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Snel", "Bijzonder", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Gegrilde tonijnsteak met sesamkorst, rosé van binnen",
    vanSchaap: ["4 tonijnsteaks (à 150 g, sushi-kwaliteit)"],
    vanSupermarkt: [
      "Sesamzaad",
      "Sojasaus",
      "1 limoen",
      "Verse gember",
      "Honing",
      "Zonnebloemolie",
      "Rijst en broccoli als bijgerecht",
    ],
    bereidingswijze: [
      "Haal de tonijn 15 minuten voor het bakken uit de koelkast.",
      "Roer een dip van 4 el sojasaus, het sap van een halve limoen, 1 tl geraspte gember en 1 tl honing.",
      "Dep de steaks droog, wrijf in met olie en druk het sesamzaad aan beide kanten aan.",
      "Verhit een grillpan op hoog vuur tot hij rookt.",
      "Gril de tonijn 1 à 1,5 minuut per kant — de kern moet rosé blijven, anders wordt hij droog.",
      "Snijd in plakken en serveer met de dip, rijst en broccoli.",
    ],
    verhaal:
      "Tonijn is het mooist als de kern nog rood-rosé is. Doorbakken tonijn is zonde van deze prachtige vis — durf kort te bakken.",
    seoKeywords: "tonijnsteak bakken recept, gegrilde tonijn sesam, verse tonijn recept",
  },
  {
    slug: "gestoomde-makreel-puree",
    title: "Gestoomde makreel met aardappelpuree en spinazie",
    subtitle: "Onze gestoomde makreel hoeft alleen nog op tafel — comfortfood in 20 minuten",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — makreel op z'n vetst juli t/m september",
    fotoLabel: "Gestoomde makreel met aardappelpuree en spinazie",
    vanSchaap: ["2 grote gestoomde makrelen (of 4 kleine)"],
    vanSupermarkt: [
      "1 kg kruimige aardappelen",
      "450 g verse spinazie",
      "Melk en boter",
      "Nootmuskaat",
      "Mosterd",
      "1 citroen",
    ],
    bereidingswijze: [
      "Kook de aardappelen in 15 minuten gaar en stamp tot puree met warme melk, boter en nootmuskaat.",
      "Laat de spinazie in een grote pan slinken met een klontje boter en breng op smaak.",
      "Haal intussen de makreel van de graat: trek het vel eraf en til de filets in grote stukken van de graat.",
      "Verwarm de makreel desgewenst 5 minuten in een oven van 160°C — op kamertemperatuur kan ook.",
      "Serveer de makreel op de puree met spinazie en een lepeltje mosterd of een kneep citroen.",
    ],
    verhaal:
      "Onze makreel wordt vers gestoomd — het werk is al gedaan. Makreel zit boordevol omega-3; dit is misschien wel de gezondste snelle maaltijd die er bestaat.",
    seoKeywords: "gestoomde makreel recept, makreel met puree, makreel avondeten",
  },
  {
    slug: "snelle-viscurry-kabeljauw",
    title: "Snelle viscurry met kabeljauw",
    subtitle: "Milde kokoscurry waar ook kinderen blij van worden",
    tijd: "25 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Milde viscurry met kokosmelk en rijst",
    vanSchaap: ["600 g kabeljauwfilet (of wijting), in blokken van 3 cm"],
    vanSupermarkt: [
      "400 ml kokosmelk",
      "2 el milde currypasta (korma of gele curry)",
      "1 ui + 1 rode paprika",
      "150 g sugarsnaps",
      "1 limoen",
      "Verse koriander",
      "Rijst",
    ],
    bereidingswijze: [
      "Zet de rijst op.",
      "Fruit de gesnipperde ui 3 minuten in olie, voeg de currypasta toe en bak 1 minuut mee.",
      "Voeg paprikareepjes en kokosmelk toe en laat 5 minuten zachtjes koken.",
      "Voeg de sugarsnaps toe en daarna de visblokken; laat 5–6 minuten zachtjes pocheren — niet roeren, niet koken, dan valt de vis uit elkaar.",
      "Breng op smaak met limoensap en zout.",
      "Serveer op rijst met koriander.",
    ],
    verhaal:
      "Pocheer de vis zachtjes in de saus in plaats van te bakken — hij blijft heel en wordt boterzacht. Wijting werkt hier net zo goed en is voordeliger.",
    seoKeywords: "viscurry recept, kabeljauw curry kokosmelk, snelle viscurry",
  },
  {
    slug: "poke-bowl-verse-zalm",
    title: "Poké bowl met verse zalm",
    subtitle: "Frisse bowl met blokjes rauwe zalm — gezonder wordt het niet",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Gezond", "Zomers"],
    porties: 2,
    seizoen: "Jaarrond",
    fotoLabel: "Poké bowl met rauwe zalm, avocado en edamame",
    vanSchaap: [
      "250 g verse Varlaks zalmfilet, sushi-kwaliteit — zeg erbij dat het voor rauwe bereiding is",
    ],
    vanSupermarkt: [
      "200 g sushirijst",
      "Sojasaus en sesamolie",
      "1 avocado",
      "½ komkommer + 1 wortel",
      "Edamame (diepvries)",
      "Sesamzaad",
      "Mayonaise + sriracha (optioneel)",
    ],
    bereidingswijze: [
      "Kook de sushirijst volgens de verpakking en laat afkoelen tot lauwwarm.",
      "Snijd de zalm in blokjes van 2 cm en marineer 10 minuten in 2 el sojasaus en 1 tl sesamolie.",
      "Snijd avocado, komkommer en wortel; kook de edamame 3 minuten.",
      "Verdeel de rijst over kommen en schik alles erop.",
      "Werk af met sesamzaad en eventueel sriracha-mayo.",
    ],
    verhaal:
      "Voor rauwe bereiding is verse, goed gekoelde zalm essentieel — zeg het er bij ons even bij, dan geven we het mooiste middenstuk mee.",
    seoKeywords: "poke bowl zalm recept, zelf poke bowl maken, rauwe zalm bowl",
  },
  {
    slug: "teriyaki-zalm-rijst",
    title: "Teriyaki-zalm met rijst en broccoli",
    subtitle: "Plakkerig-zoete glazuurlaag, klaar in 20 minuten",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Geglaceerde teriyaki-zalm met rijst en sesam",
    vanSchaap: ["4 Varlaks zalmfilets (à 150 g), zonder huid"],
    vanSupermarkt: [
      "6 el sojasaus + 2 el honing",
      "1 teen knoflook",
      "Verse gember",
      "Rijst",
      "1 broccoli",
      "Sesamzaad",
    ],
    bereidingswijze: [
      "Zet de rijst op en kook de broccoliroosjes 4–5 minuten beetgaar.",
      "Meng sojasaus, honing, geperste knoflook en 1 tl geraspte gember tot teriyakisaus.",
      "Bak de zalmfilets 2 minuten per kant in een hete pan met wat olie.",
      "Giet de saus erbij en laat 2–3 minuten zachtjes pruttelen; lepel de saus steeds over de zalm tot hij glanst.",
      "Serveer op rijst met broccoli en sesamzaad.",
    ],
    verhaal:
      "De saus karamelliseert snel — blijf erbij en zet het vuur laag zodra hij borrelt. Kinderen die 'geen vis lusten' gaan hier vaak om.",
    seoKeywords: "teriyaki zalm recept, zalm teriyaki rijst, zoete zalm recept",
  },
  {
    slug: "pasta-verse-tonijn-tomaat",
    title: "Pasta met verse tonijn, tomaat en olijven",
    subtitle: "Siciliaanse klassieker met verse tonijn in plaats van blik",
    tijd: "25 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Zomers"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Spaghetti met verse tonijn, kerstomaten en olijven",
    vanSchaap: ["400 g verse tonijn, in blokjes van 2 cm"],
    vanSupermarkt: [
      "400 g spaghetti",
      "400 g kerstomaten",
      "2 tenen knoflook",
      "Zwarte olijven + kappertjes",
      "Chilivlokken",
      "Verse peterselie",
      "Olijfolie",
    ],
    bereidingswijze: [
      "Kook de spaghetti beetgaar.",
      "Bak knoflook en chilivlokken 1 minuut in ruim olijfolie, voeg de gehalveerde kerstomaten toe en laat 8 minuten zachtjes koken tot een saus.",
      "Roer olijven en kappertjes erdoor.",
      "Bak de tonijnblokjes in een aparte hete pan 1 minuut rondom aan — kern rosé.",
      "Schep pasta, saus en tonijn om met een scheut kookvocht.",
      "Serveer met peterselie.",
    ],
    verhaal:
      "Bak de tonijn apart en kort, en voeg hem op het laatst toe — meegekookte tonijn wordt droog en korrelig.",
    seoKeywords: "pasta verse tonijn recept, spaghetti tonijn tomaat, verse tonijn pasta",
  },

  // ── HOLLANDSE KLASSIEKERS ─────────────────────────────────────────
  {
    slug: "broodje-haring-uitjes",
    title: "Broodje Hollandse Nieuwe met uitjes",
    subtitle: "De enige juiste manier: zacht broodje, verse haring, uitjes en zuur",
    tijd: "5 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Zomers"],
    porties: 4,
    seizoen: "Hollandse Nieuwe: half juni t/m juli — haring tot in het najaar",
    fotoLabel: "Broodje haring met gesnipperde ui",
    highlight: "Seizoenstopper",
    vanSchaap: ["4 verse haringen, schoongemaakt"],
    vanSupermarkt: ["4 zachte witte bolletjes", "1 ui, fijngesnipperd", "Augurken"],
    bereidingswijze: [
      "Snijd de bolletjes open.",
      "Leg in elk broodje een haring — heel of in stukjes, beide mag.",
      "Bestrooi royaal met uitjes.",
      "Serveer met augurk erbij. Klaar.",
    ],
    verhaal:
      "Vlaggetjesdag in juni luidt elk jaar het nieuwe haringseizoen in — dan is de Hollandse Nieuwe op z'n romigst en vetst, en zit hij vol omega-3. Bij ons altijd vers gesneden op het moment dat u bestelt.",
    seoKeywords: "broodje haring, hollandse nieuwe recept, broodje hollandse nieuwe",
  },
  {
    slug: "kibbeling-knoflooksaus-salade",
    title: "Kibbeling met zelfgemaakte knoflooksaus en frisse salade",
    subtitle: "Haal de kibbeling warm bij ons — maak thuis alleen de saus en salade",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Goudbruine kibbeling met knoflooksaus",
    vanSchaap: ["600–800 g verse kibbeling, warm gebakken"],
    vanSupermarkt: [
      "Mayonaise + Griekse yoghurt",
      "1 teen knoflook",
      "1 citroen",
      "Verse dille of peterselie",
      "IJsbergsla, komkommer, tomaat",
      "Friet (optioneel)",
    ],
    bereidingswijze: [
      "Roer 5 el mayonaise met 3 el yoghurt, 1 geperste teen knoflook, citroensap en fijngehakte dille tot een saus.",
      "Maak een frisse salade van sla, komkommer en tomaat.",
      "Haal de kibbeling vlak voor het eten warm bij ons op — of verwarm hem 8 minuten in een oven van 180°C. Niet de magnetron: dan wordt hij zacht.",
      "Serveer direct met de saus en salade.",
    ],
    verhaal:
      "Het geheim van goede kibbeling is vers bakken — daarom bakken wij de hele dag door. De magnetron is de doodsteek voor een krokant korstje; de oven is z'n redding.",
    seoKeywords: "kibbeling saus recept, knoflooksaus kibbeling, kibbeling maaltijd",
  },
  {
    slug: "lekkerbek-koolsalade",
    title: "Lekkerbek met frisse koolsalade en remoulade",
    subtitle: "Knapperige lekkerbek als volwaardige maaltijd",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Lekkerbek met koolsalade en remoulade",
    vanSchaap: ["4 verse lekkerbekken"],
    vanSupermarkt: [
      "¼ witte kool of een zak koolsalade-mix",
      "1 wortel",
      "Mayonaise, yoghurt, azijn, suiker",
      "Augurk + kappertjes",
      "Verse peterselie",
      "1 citroen",
      "Krieltjes",
    ],
    bereidingswijze: [
      "Schaaf kool en wortel fijn — of gebruik een zak mix.",
      "Meng met 3 el mayonaise, 2 el yoghurt, 1 el azijn en 1 tl suiker; laat 10 minuten intrekken.",
      "Roer een snelle remoulade: mayonaise met fijngehakte augurk, kappertjes en peterselie.",
      "Kook de krieltjes in 12–15 minuten gaar.",
      "Verwarm de lekkerbek 8–10 minuten in een oven van 180°C tot hij weer knispert.",
      "Serveer met de koolsalade, remoulade en citroen.",
    ],
    verhaal:
      "De lekkerbek — gebakken wijting in beslag — is het Nederlandse antwoord op fish & chips. Met koolsalade erbij maak je er een complete maaltijd van.",
    seoKeywords: "lekkerbek recept, lekkerbek maaltijd, koolsalade bij vis",
  },
  {
    slug: "vissoep-rouille-croutons",
    title: "Rijke vissoep met rouille en croutons",
    subtitle: "Onze huisgemaakte vissoep, opgediend zoals in Frankrijk",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Bijzonder"],
    porties: 4,
    seizoen: "Jaarrond — op z'n best in herfst en winter",
    fotoLabel: "Vissoep met croutons en rouille",
    vanSchaap: [
      "1 liter huisgemaakte vissoep",
      "Optioneel: 200 g extra kabeljauwblokjes of garnalen",
    ],
    vanSupermarkt: [
      "Stokbrood",
      "Mayonaise + 1 teen knoflook",
      "Paprikapoeder",
      "Snufje saffraan of kurkuma",
      "Geraspte oude kaas of Gruyère",
    ],
    bereidingswijze: [
      "Verwarm de vissoep zachtjes — niet hard laten koken.",
      "Wilt u hem rijker maken: voeg de laatste 5 minuten visblokjes of garnalen toe.",
      "Maak de rouille: roer mayonaise met geperste knoflook, ½ tl paprikapoeder en een snuf saffraan.",
      "Snijd het stokbrood in plakjes en rooster ze 5 minuten in een oven van 200°C.",
      "Serveer de soep met croutons, een lepel rouille en geraspte kaas — laat de croutons in de soep zakken.",
    ],
    verhaal:
      "Onze vissoep wordt in de winkel gemaakt met echte visbouillon. De Franse opdientruc — crouton, rouille, kaas — maakt er thuis een feestje van.",
    seoKeywords: "vissoep recept, vissoep rouille, vissoep serveren",
  },
  {
    slug: "hollandse-garnalencocktail",
    title: "Hollandse garnalencocktail",
    subtitle: "Retro-klassieker die nooit verveelt — in 15 minuten klaar",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel"],
    porties: 4,
    seizoen: "Jaarrond — garnalen op hun best in voor- en najaar",
    fotoLabel: "Garnalencocktail in glas met cocktailsaus",
    vanSchaap: ["300 g Hollandse garnalen, gepeld — op aanvraag, bel een dag van tevoren"],
    vanSupermarkt: [
      "IJsbergsla",
      "Mayonaise + tomatenketchup",
      "1 citroen",
      "Druppel cognac of whisky (optioneel)",
      "Cayennepeper",
      "½ komkommer",
    ],
    bereidingswijze: [
      "Roer de cocktailsaus: 5 el mayonaise, 2 el ketchup, een kneep citroen, eventueel ½ tl cognac en een snuf cayenne.",
      "Snijd de sla in dunne reepjes.",
      "Verdeel de sla over 4 glazen of coupes.",
      "Schep de garnalen erop en lepel de saus eroverheen.",
      "Garneer met komkommer en citroen. Serveer goed koud.",
    ],
    verhaal:
      "Hollandse garnalen zijn klein maar hebben de meeste smaak van alle garnalen. Wij hebben ze op aanvraag — even bellen en ze liggen voor u klaar.",
    seoKeywords: "garnalencocktail recept, hollandse garnalen cocktail, garnalencocktail voorgerecht",
  },
  {
    slug: "toast-gerookte-paling",
    title: "Toast met gerookte paling en mierikswortelcrème",
    subtitle: "Het luxe borrelhapje dat in 10 minuten op tafel staat",
    tijd: "10 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Toast met gerookte paling en bieslook",
    vanSchaap: ["200 g gerookte paling, gefileerd"],
    vanSupermarkt: [
      "Brioche of casinobrood",
      "Crème fraîche",
      "Mierikswortel (potje)",
      "1 citroen",
      "Bieslook",
    ],
    bereidingswijze: [
      "Rooster het brood goudbruin en snijd het in nette vierkanten.",
      "Roer 4 el crème fraîche met 1 tl mierikswortel en wat citroensap.",
      "Bestrijk de toast met de crème.",
      "Verdeel de paling erover en werk af met bieslook en zwarte peper.",
    ],
    verhaal:
      "Goede gerookte paling is glanzend, stevig en niet droog — zo komt hij bij ons uit de rokerij. Meer dan dit recept heeft hij niet nodig.",
    seoKeywords: "gerookte paling toast, paling borrelhapje, recept gerookte paling",
  },

  // ── GEZOND ────────────────────────────────────────────────────────
  {
    slug: "kabeljauw-oven-tomaat-olijven",
    title: "Kabeljauw uit de oven met tomaat en olijven",
    subtitle: "Mediterrane ovenschotel — alles in één schaal",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — kabeljauw op z'n best januari t/m maart",
    fotoLabel: "Kabeljauw uit de oven met kerstomaten en olijven",
    vanSchaap: ["4 kabeljauwfilets (à 150 g)"],
    vanSupermarkt: [
      "500 g kerstomaten",
      "Zwarte olijven + kappertjes",
      "2 tenen knoflook + 1 rode ui",
      "1 citroen",
      "Tijm of oregano",
      "Olijfolie",
      "Stokbrood of rijst",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C.",
      "Meng kerstomaten, olijven, kappertjes, knoflook en ui in parten met olijfolie in een ovenschaal; rooster 12 minuten.",
      "Bestrooi de kabeljauw met zout, peper en tijm.",
      "Leg de filets tussen de groenten en besprenkel met olie.",
      "Bak nog 12–14 minuten tot de vis in witte vlokken uiteenvalt.",
      "Serveer met stokbrood om de jus op te deppen.",
    ],
    verhaal:
      "Eén ovenschaal, geen gedoe. De tomatenjus die ontstaat is misschien wel het lekkerste deel — brood erbij is verplicht.",
    seoKeywords: "kabeljauw oven recept, kabeljauw tomaat olijven, mediterrane visschotel",
  },
  {
    slug: "vispakketje-oven-groenten",
    title: "Vispakketje uit de oven met groenten",
    subtitle: "Vis in een pakketje van bakpapier — sappig gegarandeerd",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Makkelijk", "Gezond", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Vis en papillote — vis in bakpapier met groenten",
    vanSchaap: ["4 filets witvis naar keuze (kabeljauw, wijting) of zalm, à 150 g"],
    vanSupermarkt: [
      "1 courgette + 1 wortel + 1 prei",
      "1 citroen",
      "Scheutje witte wijn of visbouillon",
      "Boter",
      "Dille of peterselie",
      "Bakpapier",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C.",
      "Snijd de groenten in dunne reepjes.",
      "Leg per persoon een vel bakpapier klaar, verdeel de groenten in het midden en leg de vis erop.",
      "Kruid met zout en peper, leg een plakje citroen en een klontje boter op de vis en schenk er 1 el wijn bij.",
      "Vouw het papier dicht tot een goed gesloten pakketje.",
      "Bak 15–18 minuten.",
      "Serveer de pakketjes gesloten op het bord — het openmaken is het feestmoment.",
    ],
    verhaal:
      "In een pakketje gaart vis in zijn eigen stoom: hij kan vrijwel niet droog worden. Ideaal voor wie bang is om vis te verprutsen — en kinderen vinden het openmaken geweldig.",
    seoKeywords: "vispakketje oven recept, vis en papillote, vis met groenten uit de oven",
  },
  {
    slug: "zalm-traybake-groenten",
    title: "Zalm-traybake met geroosterde groenten",
    subtitle: "Alles op één bakplaat, de oven doet het werk",
    tijd: "35 min",
    moeilijkheid: "Makkelijk",
    tags: ["Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Zalm op bakplaat met geroosterde groenten",
    vanSchaap: ["4 Varlaks zalmfilets (à 150 g)"],
    vanSupermarkt: [
      "600 g krieltjes",
      "1 broccoli + 1 rode paprika + 1 rode ui",
      "Olijfolie",
      "Paprikapoeder",
      "Knoflook",
      "1 citroen",
      "Griekse yoghurt",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C.",
      "Halveer de krieltjes, meng met olie, zout en paprikapoeder op een bakplaat en rooster 15 minuten.",
      "Voeg broccoliroosjes, paprika en ui in parten toe; rooster 10 minuten mee.",
      "Schuif de groenten opzij, leg de zalm ertussen en bestrijk met olie, zout en peper.",
      "Bak nog 12 minuten tot de zalm net gaar is.",
      "Serveer met citroen en een lepel yoghurt met knoflook.",
    ],
    verhaal:
      "Eén bakplaat, vijf minuten snijwerk, en de afwas valt ook mee. Dé instapper voor wie doordeweeks gezonder wil eten.",
    seoKeywords: "zalm traybake recept, zalm bakplaat groenten, zalm uit de oven met groenten",
  },
  {
    slug: "makreelsalade-brood",
    title: "Huisgemaakte makreelsalade voor op brood",
    subtitle: "In 10 minuten een lunchspread vol omega-3",
    tijd: "10 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Makreelsalade op geroosterd brood",
    vanSchaap: ["1 gestoomde makreel (ca. 300 g visvlees)"],
    vanSupermarkt: [
      "Crème fraîche of Griekse yoghurt",
      "Mayonaise",
      "1 stengel bleekselderij + ½ rode ui",
      "1 citroen",
      "Bieslook",
      "Goed (zuurdesem)brood",
    ],
    bereidingswijze: [
      "Haal de makreel van de graat en verwijder het vel.",
      "Prak het visvlees grof met een vork.",
      "Meng met 3 el crème fraîche, 1 el mayonaise en de fijngesneden bleekselderij en rode ui.",
      "Breng op smaak met citroensap, peper en bieslook.",
      "Serveer op geroosterd brood. Blijft 2 dagen goed in de koelkast.",
    ],
    verhaal:
      "Vergeet de kant-en-klare bakjes uit de supermarkt — met onze gestoomde makreel maakt u in 10 minuten een spread die nergens mee te vergelijken is.",
    seoKeywords: "makreelsalade recept, makreelspread zelf maken, gestoomde makreel salade",
  },
  {
    slug: "viskoekjes-wijting",
    title: "Viskoekjes van wijting met citroenmayo",
    subtitle: "Krokante viskoekjes — budgetvriendelijk en kindvriendelijk",
    tijd: "35 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Met de kids", "Makkelijk"],
    porties: 4,
    seizoen: "Jaarrond — wijting op z'n best in herfst en winter",
    fotoLabel: "Goudbruin gebakken viskoekjes met citroen",
    vanSchaap: ["500 g wijtingfilet (of kabeljauw)"],
    vanSupermarkt: [
      "400 g kruimige aardappelen",
      "1 ei",
      "Paneermeel",
      "1 citroen",
      "Verse peterselie",
      "Mayonaise",
      "Zonnebloemolie",
      "Doperwten als bijgerecht",
    ],
    bereidingswijze: [
      "Kook de aardappelen gaar en stamp grof; laat iets afkoelen.",
      "Pocheer de wijting 4 minuten in zachtjes kokend water met zout; laat uitlekken en prak.",
      "Meng vis, aardappel, peterselie, citroenrasp, zout en peper; vorm er 8 koekjes van.",
      "Haal ze door losgeklopt ei en dan door het paneermeel.",
      "Laat 10 minuten opstijven in de koelkast.",
      "Bak de koekjes 3–4 minuten per kant goudbruin in een laagje olie.",
      "Serveer met citroenmayonaise en doperwten.",
    ],
    verhaal:
      "De ideale manier om kinderen aan de vis te krijgen — laat ze meehelpen met koekjes draaien. Wijting is er perfect voor: fijn van smaak en vriendelijk geprijsd.",
    seoKeywords: "viskoekjes recept, viskoekjes wijting, visburger zelf maken",
  },

  // ── FEESTELIJK MAAR SIMPEL ────────────────────────────────────────
  {
    slug: "oesters-sjalottenazijn",
    title: "Oesters klassiek met sjalottenazijn",
    subtitle: "Oesters serveren zoals het hoort — met drie klassieke garnituren",
    tijd: "15 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Bijzonder"],
    porties: 4,
    seizoen: "September t/m april — de maanden met een 'r'",
    fotoLabel: "Verse oesters op ijs met citroen",
    highlight: "Feestdagen-favoriet",
    vanSchaap: ["12 verse Fine de Claire oesters — wij openen ze desgewenst voor u"],
    vanSupermarkt: [
      "1 sjalot",
      "Rode wijnazijn",
      "1 citroen",
      "Tabasco",
      "Bruinbrood + roomboter",
      "Grof zeezout of ijs voor het opdienen",
    ],
    bereidingswijze: [
      "Maak de mignonette: roer 1 fijngesnipperde sjalot door 4 el rode wijnazijn met versgemalen peper.",
      "Schik een laag grof zout of gecrusht ijs op een schaal.",
      "Open de oesters — of laat dit door ons doen: houd de oester in een theedoek, wrik het mes bij het scharnier naar binnen en snijd de spier los. Bewaar het vocht in de schelp.",
      "Schik de oesters op de schaal.",
      "Serveer met de mignonette, citroenpartjes en tabasco, plus bruinbrood met boter.",
    ],
    verhaal:
      "Het oesterseizoen loopt traditioneel van september t/m april — de maanden met een 'r'. Een verse oester ruikt naar zee, nooit 'vissig'. Openen spannend? Wij doen het graag voor u, vlak voor uw etentje.",
    seoKeywords: "oesters serveren, oesters openen, mignonette recept oesters",
  },
  {
    slug: "gerookte-zalm-rolletjes-roomkaas",
    title: "Gerookte zalmrolletjes met roomkaas en dille",
    subtitle: "Feestelijk voorgerecht in 15 minuten — geen kookwerk",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel"],
    porties: 4,
    seizoen: "Jaarrond — topper rond de feestdagen",
    fotoLabel: "Gerookte zalmrolletjes met roomkaas",
    vanSchaap: ["200 g gerookte zalm, dungesneden"],
    vanSupermarkt: [
      "150 g roomkaas",
      "Verse dille",
      "1 citroen",
      "Kappertjes",
      "½ komkommer",
      "Rucola",
      "Toast of blini's",
    ],
    bereidingswijze: [
      "Roer de roomkaas los met fijngehakte dille, citroenrasp en peper.",
      "Leg de zalmplakken licht overlappend op plasticfolie tot een rechthoek.",
      "Bestrijk met de roomkaas en rol met behulp van de folie strak op.",
      "Laat 30 minuten opstijven in de koelkast — kan een dag vooruit.",
      "Snijd in rolletjes van 2 cm.",
      "Serveer op rucola met komkommer, kappertjes en toast.",
    ],
    verhaal:
      "Dit voorgerecht maakt u volledig vooraf — op het moment zelf alleen nog snijden en serveren. Onze ambachtelijk gerookte zalm maakt het verschil tussen 'aardig' en 'wauw'.",
    seoKeywords: "gerookte zalm voorgerecht, zalmrolletjes roomkaas, voorgerecht kerst zalm",
  },
  {
    slug: "tonijntartaar-avocado",
    title: "Tonijntartaar met avocado en sesam",
    subtitle: "Chic voorgerecht zonder kookwerk — alleen snijden en stapelen",
    tijd: "20 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Bijzonder", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Tonijntartaar gestapeld met avocado en sesam",
    vanSchaap: ["300 g verse tonijn, sushi-kwaliteit — zeg erbij: voor rauwe bereiding"],
    vanSupermarkt: [
      "2 avocado's",
      "Sojasaus + sesamolie",
      "1 limoen",
      "1 sjalot",
      "Sesamzaad + bosui",
      "Toastjes of kroepoek",
    ],
    bereidingswijze: [
      "Snijd de tonijn met een scherp mes in blokjes van een halve centimeter.",
      "Meng met 2 el sojasaus, 1 tl sesamolie, de fijngesnipperde sjalot en limoensap; laat maximaal 10 minuten marineren.",
      "Prak de avocado met limoensap, zout en peper.",
      "Schep per bord eerst een laag avocado — gebruik een serveerring of espressokopje — en dan de tartaar erop.",
      "Werk af met sesamzaad en bosui; serveer met toastjes.",
    ],
    verhaal:
      "Marineer niet langer dan 10 minuten, anders 'gaart' het zuur de tonijn grijs. Vraag bij ons om een mooi middenstuk — dat snijdt het strakst.",
    seoKeywords: "tonijntartaar recept, tartaar van tonijn avocado, voorgerecht tonijn",
  },
  {
    slug: "toast-hollandse-garnalen-avocado",
    title: "Toast met Hollandse garnalen en avocado",
    subtitle: "Luxe lunch of voorgerecht met de smaak van de Noordzee",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — garnalen op hun best in voor- en najaar",
    fotoLabel: "Toast met avocado en Hollandse garnalen",
    vanSchaap: ["200 g Hollandse garnalen — op aanvraag, geef het een dag van tevoren door"],
    vanSupermarkt: [
      "4 sneden zuurdesembrood",
      "2 avocado's",
      "1 citroen",
      "Mayonaise",
      "Cayennepeper",
      "Bieslook",
      "Radijsjes (optioneel)",
    ],
    bereidingswijze: [
      "Rooster het brood.",
      "Prak de avocado met citroensap, zout en peper.",
      "Meng de garnalen losjes met 1 el mayonaise en een snufje cayenne.",
      "Besmeer de toast met avocado en stapel de garnalen erop.",
      "Werk af met bieslook, citroenrasp en eventueel plakjes radijs.",
    ],
    verhaal:
      "De Hollandse garnaal wordt op de Noordzee gevangen en is veel smaakvoller dan grote tropische garnalen. Wij bestellen ze vers voor u — geef het een dag van tevoren door.",
    seoKeywords: "toast garnalen avocado, hollandse garnalen recept, garnalen lunch recept",
  },
];
