import type { Recept } from "./recepten";

// Praktische, doenbare recepten — met totale tijd inclusief wachttijd,
// ingrediënten uit de viswinkel + gewone supermarkt.
export const receptenPraktisch: Recept[] = [
  // ── SNEL DOORDEWEEKS ──────────────────────────────────────────────
  {
    slug: "pasta-gerookte-zalm-roomsaus",
    hoofdproduct: "gerookte-zalm-high-seas",
    title: "Pasta met gerookte zalm en roomsaus",
    subtitle: "Romige pasta met gerookte zalm, klaar in 20 minuten",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Romige tagliatelle met gerookte zalm en dille",
    vanSchaap: ["Gerookte zalm (200 g) — vraag naar de dikgesneden variant"],
    vanSupermarkt: [
      "400 g tagliatelle of penne",
      "250 ml kookroom",
      "1 sjalot + 2 tenen knoflook",
      "2 el fijngehakte dille",
      "1 citroen",
      "30 g Parmezaanse kaas",
      "1 el olijfolie",
      "Peper en zout naar smaak",
    ],
    bereidingswijze: [
      "Kook de pasta volgens de verpakking beetgaar.",
      "Fruit intussen de gesnipperde sjalot en knoflook 2 minuten in olijfolie op middelhoog vuur.",
      "Voeg de kookroom toe en laat 3–4 minuten zachtjes inkoken. Breng op smaak met peper en een kneep citroen.",
      "Scheur de gerookte zalm in stukken.",
      "Schep de pasta met een lepel kookvocht door de saus, haal de pan van het vuur en voeg de zalm toe — niet meekoken, dan blijft hij zacht.",
      "Serveer met dille en Parmezaan.",
    ],
    verhaal:
      "Voeg de zalm pas op het laatst toe, van het vuur af — zo blijft de rooksmaak intact. Vraag naar de dikgesneden variant voor dit gerecht.",
    seoKeywords: "pasta gerookte zalm recept, romige zalmpasta, snelle zalmpasta",
    keuken: "Italiaans geïnspireerd",
    veiligheid: "De gerookte zalm wordt hier van het vuur af toegevoegd. Voor kwetsbare groepen moet ook de zalm door en door worden verhit; gebruik dan eventueel verse zalm die u eerst volledig gaart.",
  },
  {
    slug: "gebakken-kabeljauw-botersaus",
    hoofdproduct: "kabeljauwfilet",
    title: "Gebakken kabeljauw met citroen-botersaus",
    subtitle: "Gebakken vis met een eenvoudige citroen-botersaus",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk"],
    porties: 4,
    seizoen: "Jaarrond — op z'n best januari t/m maart",
    fotoLabel: "Gebakken kabeljauwfilet met botersaus en citroen",
    vanSchaap: ["4 kabeljauwfilets (à 150 g)"],
    vanSupermarkt: [
      "2 el bloem",
      "75 g roomboter",
      "1 citroen",
      "2 el fijngehakte peterselie",
      "1 el kappertjes (optioneel)",
      "600 g krieltjes",
      "400 g sperziebonen",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Kook de krieltjes in circa 15–20 minuten gaar. Kook de sperziebonen in 8–10 minuten gaar.",
      "Dep de vis droog en breng op smaak. Haal licht door de bloem.",
      "Verhit 25 g boter op middelhoog vuur. Bak de vis circa 3–4 minuten aan de eerste kant en 2–4 minuten aan de tweede kant, tot gaar. Haal uit de pan.",
      "Voeg de resterende boter toe en laat lichtbruin worden. Zet het vuur laag en roer 1–2 el citroensap, peterselie en eventueel kappertjes erdoor.",
      "Serveer de vis met de saus, krieltjes en sperziebonen.",
    ],
    verhaal:
      "Kabeljauw is gaar zodra hij in stevige witte vlokken uiteenvalt. Beweeg de vis niet tijdens het bakken — dan blijft hij heel.",
    seoKeywords: "kabeljauw bakken recept, gebakken kabeljauw botersaus, kabeljauwfilet pan",
  },
  {
    slug: "gebakken-wijting-citroen",
    hoofdproduct: "wijtingfilet",
    title: "Gebakken wijting met citroen en peterselie",
    subtitle: "Een eenvoudige Noordzeevis met aardappelen en sperziebonen",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Op z'n best september t/m maart",
    fotoLabel: "Gebakken wijtingfilet met citroen",
    vanSchaap: ["4 wijtingfilets (à 125–150 g) — vraag ons ze graatvrij te maken"],
    vanSupermarkt: [
      "2 el bloem",
      "30 g boter of 2 el olijfolie",
      "1 citroen",
      "2 el fijngehakte peterselie",
      "600 g aardappelen",
      "400 g sperziebonen",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Schil de aardappelen, snijd in stukken en kook circa 15–20 minuten gaar. Kook de sperziebonen in 8–10 minuten gaar.",
      "Dep de wijting droog, bestrooi met zout en peper en haal licht door de bloem.",
      "Verhit boter of olie op middelhoog vuur.",
      "Bak de filets circa 2–3 minuten per kant. Controleer of het dikste deel gaar is.",
      "Bestrooi met peterselie en serveer met citroen, aardappelen en sperziebonen.",
    ],
    verhaal:
      "Wijting is familie van de kabeljauw maar een stuk voordeliger — een echte vergeten Noordzeevis die meer aandacht verdient.",
    seoKeywords: "wijting recept, wijting bakken, wijtingfilet pan recept",
  },
  {
    slug: "tonijnsteak-grillen-sesam",
    hoofdproduct: "tonijnfilet",
    title: "Gegrilde tonijnsteak met sesam en sojadip",
    subtitle: "Kort en krachtig grillen — van binnen mooi rosé",
    tijd: "25 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Snel", "Bijzonder", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Gegrilde tonijnsteak met sesamkorst, rosé van binnen",
    vanSchaap: [
      "4 tonijnsteaks van 150 g — bespreek geschiktheid voor rosé bereiding",
    ],
    vanSupermarkt: [
      "3 el sesamzaad",
      "4 el sojasaus",
      "1 limoen",
      "1 tl geraspte gember",
      "1 tl honing",
      "1 el zonnebloemolie",
      "300 g rijst",
      "1 broccoli",
    ],
    bereidingswijze: [
      "Kook de rijst volgens de verpakking. Kook de broccoliroosjes circa 5 minuten.",
      "Roer sojasaus, sap van een halve limoen, gember en honing tot een dip.",
      "Dep de tonijn droog, bestrijk met olie en druk het sesamzaad aan beide kanten aan.",
      "Verhit de grillpan goed zonder hem te laten roken. Gril geschikte steaks circa 1–2 minuten per kant voor rosé, afhankelijk van de dikte.",
      "Serveer met de dip, rijst en broccoli. Wilt u geen rosé vis, gaar de tonijn verder op lager vuur.",
    ],
    verhaal: "Een sesamkorst en sojadip geven tonijn veel smaak. Rosé bereiding vraagt om geschikte vis; bespreek dit vooraf. De baktijd hangt af van de dikte van de steak.",
    seoKeywords: "tonijnsteak bakken recept, gegrilde tonijn sesam, verse tonijn recept",
    keuken: "Aziatisch geïnspireerd",
    veiligheid: "Rosé tonijn is niet door en door verhit. Voor zwangeren, jonge kinderen, ouderen en mensen met verminderde weerstand: gaar de vis volledig.",
  },
  {
    slug: "gestoomde-makreel-puree",
    title: "Gestoomde makreel met aardappelpuree en spinazie",
    subtitle: "Reeds gegaarde makreel met aardappelpuree en spinazie",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — makreel op z'n vetst juli t/m september",
    fotoLabel: "Gestoomde makreel met aardappelpuree en spinazie",
    vanSchaap: ["2 grote gestoomde makrelen (of 4 kleine)"],
    vanSupermarkt: [
      "1 kg kruimige aardappelen",
      "450 g verse spinazie",
      "150 ml melk",
      "30 g boter",
      "Snuf nootmuskaat",
      "2 tl mosterd",
      "1 citroen",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Schil de aardappelen en snijd in stukken van circa 3 cm. Kook 15–20 minuten tot zacht, giet af en stamp met warme melk, 20 g boter en nootmuskaat.",
      "Laat de spinazie in een grote pan slinken met de resterende 10 g boter. Breng op smaak met zout en peper.",
      "Haal intussen de makreel van de graat: trek het vel eraf en til de filets in grote stukken van de graat.",
      "Serveer de reeds gegaarde makreel koud uit de koelkast, of verwarm afgedekt in een oven van 160°C tot ook het midden goed heet is. Voor kwetsbare groepen moet gerookte vis door en door verhit zijn.",
      "Serveer de makreel op de puree met spinazie en een lepeltje mosterd of een kneep citroen.",
    ],
    verhaal: "Gebruik makreel die al gestoomd en gaar is, geen rauwe makreel. Maak de puree en spinazie terwijl u de vis zorgvuldig van vel en graten ontdoet.",
    seoKeywords: "gestoomde makreel recept, makreel met puree, makreel avondeten",
  },
  {
    slug: "snelle-viscurry-kabeljauw",
    hoofdproduct: "kabeljauwfilet",
    title: "Snelle viscurry met kabeljauw",
    subtitle: "Milde kokoscurry waar ook kinderen blij van worden",
    tijd: "25 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Milde viscurry met kokosmelk en rijst",
    vanSchaap: ["600 g kabeljauwfilet (of wijting), in blokken van 3 cm"],
    vanSupermarkt: [
      "400 ml kokosmelk",
      "2 el milde currypasta",
      "1 ui + 1 rode paprika",
      "150 g sugarsnaps",
      "1 limoen",
      "2 el fijngehakte koriander",
      "300 g rijst",
      "1 el olie",
      "Zout naar smaak",
    ],
    bereidingswijze: [
      "Zet de rijst op.",
      "Fruit de gesnipperde ui 3 minuten in olie, voeg de currypasta toe en bak 1 minuut mee.",
      "Voeg paprikareepjes en kokosmelk toe en laat 5 minuten zachtjes koken.",
      "Voeg de sugarsnaps en visblokken toe. Laat 5–8 minuten zachtjes pocheren tot de vis ook in het midden gaar is. Roer voorzichtig en laat de saus niet hard koken.",
      "Breng op smaak met limoensap en zout.",
      "Serveer op rijst met koriander.",
    ],
    verhaal:
      "Pocheer de vis zachtjes in de saus in plaats van te bakken — hij blijft heel en wordt boterzacht. Wijting werkt hier net zo goed en is voordeliger.",
    seoKeywords: "viscurry recept, kabeljauw curry kokosmelk, snelle viscurry",
    keuken: "Aziatisch geïnspireerd",
  },
  {
    slug: "poke-bowl-verse-zalm",
    hoofdproduct: "varlaks-zalm",
    title: "Poké bowl met verse zalm",
    subtitle: "Rijstbowl met zalm, avocado, komkommer en edamame",
    tijd: "35 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Gezond", "Zomers"],
    porties: 2,
    seizoen: "Jaarrond",
    fotoLabel: "Poké bowl met rauwe zalm, avocado en edamame",
    vanSchaap: [
      "250 g Varlaks zalmfilet — vraag expliciet naar geschiktheid en behandeling voor rauwe consumptie",
    ],
    vanSupermarkt: [
      "200 g sushirijst",
      "2 el sojasaus + 1 tl sesamolie",
      "1 avocado",
      "½ komkommer + 1 wortel",
      "100 g edamame uit de diepvries",
      "1 el sesamzaad",
      "2 el mayonaise + ½ tl sriracha (optioneel)",
    ],
    bereidingswijze: [
      "Kook de rijst volgens de verpakking en spreid uit op een schaal om af te koelen. Laat niet onnodig lang buiten de koelkast staan.",
      "Snijd geschikte zalm in blokjes en meng met sojasaus en sesamolie. Marineer 10 minuten in de koelkast. Gebruik anders volledig gebakken zalm.",
      "Snijd avocado, komkommer en wortel. Bereid de edamame volgens de verpakking en laat afkoelen.",
      "Verdeel rijst en groenten over twee kommen. Voeg de zalm pas vlak voor het eten toe.",
      "Bestrooi met sesamzaad en eventueel sriracha-mayonaise. Serveer direct.",
    ],
    verhaal: "Een rijstbowl is eenvoudig, maar koken en afkoelen van de rijst kost tijd. Rauw eten vraagt bovendien om geschikte vis en een goede koudeketen; met volledig gebakken zalm is dit ook lekker.",
    seoKeywords: "poke bowl zalm recept, zelf poke bowl maken, rauwe zalm bowl",
    keuken: "Hawaïaans geïnspireerd",
    veiligheid: "Gebruik niet zomaar verse zalm voor rauwe consumptie. Vraag de viswinkel welke vis en behandeling geschikt zijn. Kwetsbare groepen kiezen volledig gebakken zalm.",
  },
  {
    slug: "teriyaki-zalm-rijst",
    hoofdproduct: "varlaks-zalm",
    title: "Teriyaki-zalm met rijst en broccoli",
    subtitle: "Plakkerig-zoete glazuurlaag, klaar in 20 minuten",
    tijd: "20 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Geglaceerde teriyaki-zalm met rijst en sesam",
    vanSchaap: ["4 Varlaks zalmfilets (à 150 g), zonder huid"],
    vanSupermarkt: [
      "6 el sojasaus + 2 el honing",
      "1 teen knoflook",
      "1 tl geraspte gember",
      "300 g rijst",
      "1 broccoli",
      "1 el sesamzaad",
      "1 el olie",
    ],
    bereidingswijze: [
      "Kook de rijst volgens de verpakking. Kook de broccoliroosjes in circa 5 minuten gaar.",
      "Meng sojasaus, honing, geperste knoflook en gember.",
      "Bak de zalm circa 3 minuten per kant in olie op middelhoog vuur.",
      "Zet het vuur laag en voeg de saus toe. Laat enkele minuten zachtjes pruttelen; schep de saus over de vis. Controleer of de zalm ook in het dikste deel gaar is.",
      "Serveer met rijst, broccoli en sesamzaad.",
    ],
    verhaal:
      "De saus karamelliseert snel — blijf erbij en zet het vuur laag zodra hij borrelt. Kinderen die 'geen vis lusten' gaan hier vaak om.",
    seoKeywords: "teriyaki zalm recept, zalm teriyaki rijst, zoete zalm recept",
    keuken: "Japans geïnspireerd",
  },
  {
    slug: "pasta-verse-tonijn-tomaat",
    hoofdproduct: "tonijnfilet",
    title: "Pasta met verse tonijn, tomaat en olijven",
    subtitle: "Siciliaanse klassieker met verse tonijn in plaats van blik",
    tijd: "25 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Zomers"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Spaghetti met verse tonijn, kerstomaten en olijven",
    vanSchaap: ["400 g verse tonijn, in blokjes van 2 cm"],
    vanSupermarkt: [
      "400 g spaghetti",
      "400 g kerstomaten",
      "2 tenen knoflook",
      "50 g zwarte olijven + 1 el kappertjes",
      "Snuf chilivlokken",
      "2 el fijngehakte peterselie",
      "2 el olijfolie",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Kook de spaghetti volgens de verpakking beetgaar en bewaar wat kookvocht.",
      "Bak gehakte knoflook en chilivlokken 1 minuut in 1 el olie. Voeg gehalveerde tomaten toe en laat 8 minuten zachtjes koken.",
      "Roer olijven en kappertjes door de saus.",
      "Bak de tonijnblokjes in de overige olie circa 3–4 minuten rondom tot gaar. Vermijd onnodig lang bakken.",
      "Schep pasta, saus en tonijn door elkaar met een scheut kookvocht. Breng op smaak en voeg peterselie toe.",
    ],
    verhaal: "Bak de tonijnblokjes apart en voeg ze pas aan het einde toe. Zo voorkomt u dat ze tijdens het inkoken van de tomatensaus droog worden.",
    seoKeywords: "pasta verse tonijn recept, spaghetti tonijn tomaat, verse tonijn pasta",
    keuken: "Italiaans",
  },

  // ── HOLLANDSE KLASSIEKERS ─────────────────────────────────────────
  {
    slug: "broodje-haring-uitjes",
    hoofdproduct: "haring",
    title: "Broodje Hollandse Nieuwe met uitjes",
    subtitle: "De enige juiste manier: zacht broodje, verse haring, uitjes en zuur",
    tijd: "5 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Zomers"],
    porties: 4,
    seizoen: "Jaarrond; Hollandse Nieuwe vanaf de start van het nieuwe seizoen",
    fotoLabel: "Broodje haring met gesnipperde ui",
    highlight: "Seizoenstopper",
    vanSchaap: ["4 verse haringen, schoongemaakt"],
    vanSupermarkt: ["4 zachte witte bolletjes", "1 ui, fijngesnipperd", "Augurken"],
    bereidingswijze: [
      "Snijd de bolletjes open.",
      "Leg in elk broodje een haring — heel of in stukjes, beide mag.",
      "Bestrooi royaal met uitjes.",
      "Serveer met augurk erbij. Klaar.",
    ],
    verhaal:
      "Vlaggetjesdag in juni luidt elk jaar het nieuwe haringseizoen in — dan is de Hollandse Nieuwe op z'n romigst en vetst, en zit hij vol omega-3. Bij ons altijd vers gesneden op het moment dat u bestelt.",
    seoKeywords: "broodje haring, hollandse nieuwe recept, broodje hollandse nieuwe",
  },
  {
    slug: "kibbeling-ravigotesaus-salade",
    hoofdproduct: "kibbeling",
    title: "Kibbeling met zelfgemaakte ravigotesaus en frisse salade",
    subtitle: "Haal de kibbeling warm bij ons — maak thuis alleen de saus en salade",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Goudbruine kibbeling met ravigotesaus",
    vanSchaap: ["600–800 g verse kibbeling, warm gebakken"],
    vanSupermarkt: [
      "5 el mayonaise + 3 el Griekse yoghurt",
      "2 kleine augurken + 1 kleine sjalot",
      "1 el kappertjes + 1 tl mosterd",
      "1 citroen",
      "1 el fijngehakte peterselie",
      "½ ijsbergsla",
      "½ komkommer",
      "2 tomaten",
      "600 g friet (optioneel; extra baktijd volgens verpakking)",
    ],
    bereidingswijze: [
      "Snijd de augurken, sjalot en kappertjes heel fijn. Meng met 5 el mayonaise, 3 el yoghurt, 1 tl mosterd, 1 tl citroensap en de peterselie tot een frisse ravigotesaus.",
      "Maak een frisse salade van sla, komkommer en tomaat.",
      "Haal de kibbeling vlak voor het eten warm bij ons op — of verwarm hem circa 8 minuten in een oven van 180°C tot ook het midden goed heet is. Niet de magnetron: dan wordt hij zacht.",
      "Serveer direct met de saus en salade. Bereid eventuele friet volgens de verpakking.",
    ],
    verhaal:
      "Het geheim van goede kibbeling is vers bakken — daarom bakken wij de hele dag door. De magnetron is de doodsteek voor een krokant korstje; de oven is z'n redding.",
    seoKeywords: "kibbeling saus recept, ravigotesaus kibbeling, kibbeling maaltijd",
  },
  {
    slug: "lekkerbek-koolsalade",
    hoofdproduct: "lekkerbek",
    title: "Lekkerbek met frisse koolsalade en remoulade",
    subtitle: "Knapperige lekkerbek als volwaardige maaltijd",
    tijd: "30 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Lekkerbek met koolsalade en remoulade",
    vanSchaap: [
      "4 reeds gebakken lekkerbekken",
    ],
    vanSupermarkt: [
      "300 g witte kool",
      "1 wortel",
      "6 el mayonaise + 2 el yoghurt",
      "1 el azijn + 1 tl suiker",
      "2 augurken + 1 el kappertjes",
      "1 el fijngehakte peterselie",
      "1 citroen",
      "600 g krieltjes",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Schaaf kool en wortel fijn — of gebruik een zak mix.",
      "Meng met 3 el mayonaise, 2 el yoghurt, 1 el azijn en 1 tl suiker. Breng op smaak met zout en peper en laat 10 minuten intrekken.",
      "Roer een snelle remoulade: de resterende 3 el mayonaise met fijngehakte augurk, kappertjes en peterselie.",
      "Kook de krieltjes in 12–15 minuten gaar.",
      "Verwarm de lekkerbek circa 8–10 minuten in een oven van 180°C tot hij weer knispert en ook het midden goed heet is.",
      "Serveer met de krieltjes, koolsalade, remoulade en citroen.",
    ],
    verhaal: "Dit recept begint met reeds gebakken lekkerbek, niet met rauwe vis. Terwijl de aardappelen koken, maakt u de koolsalade en remoulade.",
    seoKeywords: "lekkerbek recept, lekkerbek maaltijd, koolsalade bij vis",
  },
  {
    slug: "vissoep-rouille-croutons",
    hoofdproduct: "vissoep",
    title: "Rijke vissoep met rouille en croutons",
    subtitle: "Onze huisgemaakte vissoep, opgediend zoals in Frankrijk",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Bijzonder"],
    porties: 4,
    seizoen: "Jaarrond — op z'n best in herfst en winter",
    fotoLabel: "Vissoep met croutons en rouille",
    vanSchaap: [
      "1 liter bereide vissoep — vraag naar beschikbaarheid",
      "200 g rauwe kabeljauwblokjes (optioneel)",
    ],
    vanSupermarkt: [
      "½ stokbrood",
      "4 el mayonaise + 1 teen knoflook",
      "½ tl paprikapoeder",
      "Snuf saffraan of kurkuma",
      "40 g geraspte oude kaas of Gruyère",
    ],
    bereidingswijze: [
      "Verwarm de vissoep goed volgens het advies bij aankoop.",
      "Voeg eventueel rauwe kabeljauwblokjes toe en laat zachtjes garen tot ze ook van binnen gaar zijn; reken circa 5–8 minuten, afhankelijk van de grootte.",
      "Meng mayonaise, geperste knoflook, paprikapoeder en saffraan of kurkuma.",
      "Rooster plakjes stokbrood circa 5 minuten in een voorverwarmde oven van 200°C.",
      "Verdeel de soep over vier kommen. Serveer met brood, saus en kaas.",
    ],
    verhaal: "Begin met bereide vissoep. De broodcroutons, knoflookmayonaise in rouillestijl en kaas maken er een eenvoudig voorgerecht voor vier personen van.",
    seoKeywords: "vissoep recept, vissoep rouille, vissoep serveren",
    keuken: "Frans geïnspireerd",
  },
  {
    slug: "hollandse-garnalencocktail",
    hoofdproduct: "hollandse-garnalen",
    title: "Hollandse garnalencocktail",
    subtitle: "Retro-klassieker die nooit verveelt — in 15 minuten klaar",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel"],
    porties: 4,
    seizoen: "Jaarrond — garnalen op hun best in voor- en najaar",
    fotoLabel: "Garnalencocktail in glas met cocktailsaus",
    vanSchaap: ["300 g gepelde, gekookte Hollandse garnalen — vraag naar de actuele beschikbaarheid"],
    vanSupermarkt: [
      "¼ ijsbergsla",
      "5 el mayonaise + 2 el ketchup",
      "1 citroen",
      "½ tl cognac of whisky (optioneel)",
      "Snuf cayennepeper",
      "½ komkommer",
    ],
    bereidingswijze: [
      "Roer de cocktailsaus: 5 el mayonaise, 2 el ketchup, een kneep citroen, eventueel ½ tl cognac en een snuf cayenne.",
      "Snijd de sla in dunne reepjes.",
      "Verdeel de sla over 4 glazen of coupes.",
      "Schep de garnalen erop en lepel de saus eroverheen.",
      "Garneer met komkommer en citroen. Serveer goed koud.",
    ],
    verhaal: "Gebruik gepelde, reeds gekookte Hollandse garnalen. Houd ze gekoeld tot het opmaken en voeg de saus vlak voor het serveren toe.",
    seoKeywords: "garnalencocktail recept, hollandse garnalen cocktail, garnalencocktail voorgerecht",
  },
  {
    slug: "toast-gerookte-paling",
    title: "Toast met gerookte paling en mierikswortelcrème",
    subtitle: "Het luxe borrelhapje dat in 10 minuten op tafel staat",
    tijd: "10 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Toast met gerookte paling en bieslook",
    vanSchaap: ["200 g gerookte paling, gefileerd"],
    vanSupermarkt: [
      "4 sneetjes brioche of casinobrood",
      "4 el crème fraîche",
      "1 tl mierikswortel uit een potje",
      "1 citroen",
      "1 el fijngeknipte bieslook",
      "Zwarte peper",
    ],
    bereidingswijze: [
      "Rooster het brood goudbruin en snijd het in nette vierkanten.",
      "Roer 4 el crème fraîche met 1 tl mierikswortel en wat citroensap.",
      "Bestrijk de toast met de crème.",
      "Verdeel de paling erover en werk af met bieslook en zwarte peper.",
    ],
    verhaal: "Gerookte paling, mierikswortel en bieslook vormen een eenvoudig borrelhapje. Gebruik gefileerde paling en controleer bij het verdelen op eventuele graten.",
    seoKeywords: "gerookte paling toast, paling borrelhapje, recept gerookte paling",
  },

  // ── GEZOND ────────────────────────────────────────────────────────
  {
    slug: "kabeljauw-oven-tomaat-olijven",
    hoofdproduct: "kabeljauwfilet",
    title: "Kabeljauw uit de oven met tomaat en olijven",
    subtitle: "Mediterrane ovenschotel — alles in één schaal",
    tijd: "40 min",
    moeilijkheid: "Makkelijk",
    tags: ["Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — kabeljauw op z'n best januari t/m maart",
    fotoLabel: "Kabeljauw uit de oven met kerstomaten en olijven",
    vanSchaap: ["4 kabeljauwfilets (à 150 g)"],
    vanSupermarkt: [
      "500 g kerstomaten",
      "50 g zwarte olijven + 1 el kappertjes",
      "2 tenen knoflook + 1 rode ui",
      "1 citroen",
      "1 tl gedroogde tijm of oregano",
      "2 el olijfolie",
      "½ stokbrood",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C (180°C hetelucht).",
      "Meng gehalveerde tomaten, olijven, kappertjes, gehakte knoflook en ui in dunne parten met 1 el olie in een ovenschaal. Rooster 12 minuten.",
      "Bestrooi de kabeljauw met zout, peper en tijm of oregano.",
      "Leg de vis tussen de groenten en besprenkel met de resterende olie en 1 el citroensap.",
      "Bak nog circa 12–18 minuten, afhankelijk van de dikte, tot de vis ook van binnen gaar is.",
      "Serveer met stokbrood en de resterende citroen in partjes.",
    ],
    verhaal:
      "Eén ovenschaal, geen gedoe. De tomatenjus die ontstaat is misschien wel het lekkerste deel — brood erbij is verplicht.",
    seoKeywords: "kabeljauw oven recept, kabeljauw tomaat olijven, mediterrane visschotel",
    keuken: "Mediterraan",
  },
  {
    slug: "vispakketje-oven-groenten",
    hoofdproduct: "kabeljauwfilet",
    title: "Vispakketje uit de oven met groenten",
    subtitle: "Vis en groenten die samen garen in bakpapier",
    tijd: "40 min",
    moeilijkheid: "Makkelijk",
    tags: ["Makkelijk", "Gezond", "Met de kids"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Vis en papillote — vis in bakpapier met groenten",
    vanSchaap: ["4 filets witvis naar keuze (kabeljauw, wijting) of zalm, à 150 g"],
    vanSupermarkt: [
      "1 courgette + 1 wortel + 1 prei",
      "1 citroen",
      "4 el visbouillon of witte wijn",
      "20 g boter",
      "2 el fijngehakte dille of peterselie",
      "Zout en peper",
      "4 ruime vellen bakpapier",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C (180°C hetelucht).",
      "Was de groenten en snijd de wortel, prei en courgette in heel dunne reepjes; dikke wortelstukken worden niet op tijd gaar.",
      "Leg vier ruime vellen bakpapier klaar. Verdeel de groenten en leg per pakket één filet erop.",
      "Voeg zout, peper, kruiden, een schijfje citroen, 5 g boter en 1 el bouillon of wijn per pakket toe.",
      "Vouw de pakketjes goed dicht en leg op een bakplaat.",
      "Bak circa 18–22 minuten. Open één pakket voorzichtig en controleer of de groenten zacht en de vis van binnen gaar zijn. Bak zo nodig enkele minuten langer.",
      "Serveer direct. Open voorzichtig: uit het pakket komt hete stoom.",
    ],
    verhaal: "Bakpapier houdt vocht vast, maar de grootte van de vis en groenten blijft belangrijk. Snijd de groenten fijn en controleer vóór het serveren één pakket op gaarheid.",
    seoKeywords: "vispakketje oven recept, vis en papillote, vis met groenten uit de oven",
    keuken: "Frans geïnspireerd",
  },
  {
    slug: "zalm-traybake-groenten",
    hoofdproduct: "varlaks-zalm",
    title: "Zalm-traybake met geroosterde groenten",
    subtitle: "Alles op één bakplaat, de oven doet het werk",
    tijd: "50 min",
    moeilijkheid: "Makkelijk",
    tags: [
      "Makkelijk",
      "Gezond",
    ],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Zalm op bakplaat met geroosterde groenten",
    vanSchaap: ["4 Varlaks zalmfilets (à 150 g)"],
    vanSupermarkt: [
      "600 g kleine krieltjes",
      "1 broccoli + 1 rode paprika + 1 rode ui",
      "3 el olijfolie",
      "1 tl paprikapoeder",
      "1 teen knoflook",
      "1 citroen",
      "150 g Griekse yoghurt",
      "Zout en peper",
      "Bakpapier",
    ],
    bereidingswijze: [
      "Verwarm de oven voor op 200°C.",
      "Halveer de krieltjes, meng met 1 el olie, zout en paprikapoeder op een met bakpapier beklede bakplaat en rooster 15 minuten.",
      "Meng broccoliroosjes, paprika en ui in parten met 1 el olie. Voeg toe aan de bakplaat en rooster 10 minuten mee.",
      "Schuif de groenten opzij, leg de zalm ertussen en bestrijk met de resterende 1 el olie, zout en peper.",
      "Bak nog 12–15 minuten tot de zalm ook in het midden gaar is en de aardappelen zacht zijn.",
      "Meng de yoghurt met geperste knoflook. Serveer met de yoghurt en citroen.",
    ],
    verhaal: "Aardappelen hebben langer nodig dan zalm. Daarom gaan ze eerst de oven in, daarna de groenten en pas als laatste de vis. Reken ook het snijden en voorverwarmen mee.",
    seoKeywords: "zalm traybake recept, zalm bakplaat groenten, zalm uit de oven met groenten",
  },
  {
    slug: "makreelsalade-brood",
    title: "Huisgemaakte makreelsalade voor op brood",
    subtitle: "In 10 minuten een lunchspread vol omega-3",
    tijd: "10 min",
    moeilijkheid: "Makkelijk",
    tags: ["Snel", "Makkelijk", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Makreelsalade op geroosterd brood",
    vanSchaap: ["1 gestoomde makreel (ca. 300 g visvlees)"],
    vanSupermarkt: [
      "3 el crème fraîche of Griekse yoghurt",
      "1 el mayonaise",
      "1 stengel bleekselderij + ½ rode ui",
      "1 citroen",
      "1 el fijngeknipte bieslook",
      "4 sneden zuurdesembrood",
      "Peper",
    ],
    bereidingswijze: [
      "Verwijder vel en graten van de reeds gestoomde makreel. Controleer de stukken zorgvuldig en prak grof.",
      "Snijd bleekselderij en ui fijn. Meng met de makreel, crème fraîche en mayonaise.",
      "Breng op smaak met 1 el citroensap, peper en bieslook.",
      "Rooster het brood en verdeel de makreelsalade erover. Serveer direct; houd overgebleven salade afgedekt en gekoeld en volg het bewaaradvies bij aankoop.",
    ],
    verhaal:
      "Vergeet de kant-en-klare bakjes uit de supermarkt — met onze gestoomde makreel maakt u in 10 minuten een spread die nergens mee te vergelijken is.",
    seoKeywords: "makreelsalade recept, makreelspread zelf maken, gestoomde makreel salade",
  },
  {
    slug: "viskoekjes-wijting",
    hoofdproduct: "wijtingfilet",
    title: "Viskoekjes van wijting met citroenmayo",
    subtitle: "Krokante viskoekjes — budgetvriendelijk en kindvriendelijk",
    tijd: "50 min",
    moeilijkheid: "Gemiddeld",
    tags: [
      "Met de kids",
    ],
    porties: 4,
    seizoen: "Jaarrond — wijting op z'n best in herfst en winter",
    fotoLabel: "Goudbruin gebakken viskoekjes met citroen",
    vanSchaap: ["500 g wijtingfilet (of kabeljauw)"],
    vanSupermarkt: [
      "400 g kruimige aardappelen",
      "1 ei",
      "75 g paneermeel",
      "1 citroen",
      "2 el fijngehakte peterselie",
      "4 el mayonaise",
      "3 el zonnebloemolie",
      "300 g doperwten",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Schil de aardappelen, snijd klein en kook circa 15 minuten gaar. Giet goed af, stamp en laat even afkoelen.",
      "Pocheer de vis zachtjes tot gaar, circa 4–6 minuten. Laat goed uitlekken en verdeel in vlokken.",
      "Meng vis, aardappel, peterselie, citroenrasp, zout en peper. Vorm acht koekjes.",
      "Haal door losgeklopt ei en paneermeel. Laat 10 minuten opstijven in de koelkast.",
      "Meng mayonaise met 1 el citroensap. Bereid de doperwten volgens de verpakking.",
      "Bak de koekjes 3–4 minuten per kant in olie tot goudbruin en goed heet van binnen. Laat dit door een volwassene doen.",
      "Serveer met de citroenmayonaise en doperwten.",
    ],
    verhaal:
      "De ideale manier om kinderen aan de vis te krijgen — laat ze meehelpen met koekjes draaien. Wijting is er perfect voor: fijn van smaak en vriendelijk geprijsd.",
    seoKeywords: "viskoekjes recept, viskoekjes wijting, visburger zelf maken",
  },

  // ── FEESTELIJK MAAR SIMPEL ────────────────────────────────────────
  {
    slug: "oesters-sjalottenazijn",
    hoofdproduct: "fine-de-claire-oesters",
    title: "Oesters klassiek met sjalottenazijn",
    subtitle: "Oesters serveren zoals het hoort — met drie klassieke garnituren",
    tijd: "15 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Bijzonder"],
    porties: 4,
    seizoen: "September t/m april — de maanden met een 'r'",
    fotoLabel: "Verse oesters op ijs met citroen",
    highlight: "Feestdagen-favoriet",
    vanSchaap: ["12 verse Fine de Claire oesters — wij openen ze desgewenst voor u"],
    vanSupermarkt: [
      "1 sjalot",
      "4 el rodewijnazijn",
      "1 citroen",
      "Tabasco naar smaak",
      "4 sneetjes bruinbrood + 20 g roomboter",
      "Grof zout of ijs voor het opdienen",
      "Zwarte peper",
    ],
    bereidingswijze: [
      "Maak de mignonette: roer 1 fijngesnipperde sjalot door 4 el rode wijnazijn met versgemalen peper.",
      "Schik een laag grof zout of gecrusht ijs op een schaal.",
      "Open de oesters — of laat dit door ons doen: houd de oester in een theedoek, wrik het mes bij het scharnier naar binnen en snijd de spier los. Bewaar het vocht in de schelp.",
      "Schik de oesters op de schaal.",
      "Serveer met de mignonette, citroenpartjes en tabasco, plus bruinbrood met boter.",
    ],
    verhaal:
      "Het oesterseizoen loopt traditioneel van september t/m april — de maanden met een 'r'. Een verse oester ruikt naar zee, nooit 'vissig'. Openen spannend? Wij doen het graag voor u, vlak voor uw etentje.",
    seoKeywords: "oesters serveren, oesters openen, mignonette recept oesters",
    keuken: "Frans geïnspireerd",
    veiligheid: "Dit recept serveert oesters rauw. Niet geschikt voor zwangeren, jonge kinderen, ouderen of mensen met verminderde weerstand. Houd de oesters gekoeld en vraag bij aankoop naar geschikt gebruik. Gebruik een oestermes en handbescherming; laat ze bij twijfel professioneel openen.",
  },
  {
    slug: "gerookte-zalm-rolletjes-roomkaas",
    hoofdproduct: "gerookte-zalm-high-seas",
    title: "Gerookte zalmrolletjes met roomkaas en dille",
    subtitle: "Feestelijk voorgerecht: 15 minuten werk en 30 minuten koelen",
    tijd: "45 min",
    moeilijkheid: "Makkelijk",
    tags: [
      "Bijzonder",
    ],
    porties: 4,
    seizoen: "Jaarrond — topper rond de feestdagen",
    fotoLabel: "Gerookte zalmrolletjes met roomkaas",
    vanSchaap: ["200 g gerookte zalm, dungesneden"],
    vanSupermarkt: [
      "150 g roomkaas",
      "2 el fijngehakte dille",
      "1 citroen",
      "1 el kappertjes",
      "½ komkommer",
      "40 g rucola",
      "8 toastjes of blini's",
      "Peper",
    ],
    bereidingswijze: [
      "Roer de roomkaas los met fijngehakte dille, citroenrasp en peper.",
      "Leg de zalmplakken licht overlappend op plasticfolie tot een rechthoek.",
      "Bestrijk met de roomkaas en rol met behulp van de folie strak op.",
      "Laat 30 minuten opstijven in de koelkast. Maak dit alleen een dag vooruit als het bewaaradvies van de vis dat toelaat.",
      "Snijd in rolletjes van 2 cm.",
      "Serveer op rucola met komkommer, kappertjes en toast.",
    ],
    verhaal:
      "Dit voorgerecht kunt u vooraf maken — op het moment zelf alleen nog snijden en serveren. Houd de rolletjes gekoeld en volg het bewaaradvies dat u bij aankoop krijgt.",
    seoKeywords: "gerookte zalm voorgerecht, zalmrolletjes roomkaas, voorgerecht kerst zalm",
    veiligheid: "De gerookte zalm wordt ongegaard gegeten. Kwetsbare groepen kiezen beter een gerecht waarbij de vis door en door wordt verhit.",
  },
  {
    slug: "tonijntartaar-avocado",
    hoofdproduct: "tonijnfilet",
    title: "Tonijntartaar met avocado en sesam",
    subtitle: "Chic voorgerecht zonder kookwerk — alleen snijden en stapelen",
    tijd: "20 min",
    moeilijkheid: "Gemiddeld",
    tags: ["Bijzonder", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond",
    fotoLabel: "Tonijntartaar gestapeld met avocado en sesam",
    vanSchaap: [
      "300 g tonijn — vraag expliciet naar geschiktheid en benodigde behandeling voor rauwe consumptie",
    ],
    vanSupermarkt: [
      "2 avocado's",
      "2 el sojasaus + 1 tl sesamolie",
      "1 limoen",
      "1 kleine sjalot",
      "1 el sesamzaad + 1 bosui",
      "8 toastjes",
      "Peper en eventueel zout",
    ],
    bereidingswijze: [
      "Snijd de tonijn met een scherp mes in blokjes van een halve centimeter.",
      "Meng met 2 el sojasaus, 1 tl sesamolie, de fijngesnipperde sjalot en limoensap; laat maximaal 10 minuten in de koelkast marineren.",
      "Prak de avocado met limoensap, zout en peper.",
      "Schep per bord eerst een laag avocado — gebruik een serveerring of espressokopje — en dan de tartaar erop.",
      "Werk af met sesamzaad en bosui; serveer met toastjes.",
    ],
    verhaal: "Snijd de tonijn vlak voor gebruik en houd hem koud. Marineer hooguit kort voor een mooie structuur. Limoensap verandert de kleur en structuur, maar maakt rauwe vis niet veilig.",
    seoKeywords: "tonijntartaar recept, tartaar van tonijn avocado, voorgerecht tonijn",
    keuken: "Aziatisch geïnspireerd",
    veiligheid: "Alleen met vis die geschikt is voor rauwe consumptie en de juiste behandeling heeft gehad. Vraag dit vooraf bij aankoop. Niet voor zwangeren, jonge kinderen, ouderen of mensen met verminderde weerstand.",
  },
  {
    slug: "toast-hollandse-garnalen-avocado",
    hoofdproduct: "hollandse-garnalen",
    title: "Toast met Hollandse garnalen en avocado",
    subtitle: "Luxe lunch of voorgerecht met de smaak van de Noordzee",
    tijd: "15 min",
    moeilijkheid: "Makkelijk",
    tags: ["Bijzonder", "Snel", "Gezond"],
    porties: 4,
    seizoen: "Jaarrond — garnalen op hun best in voor- en najaar",
    fotoLabel: "Toast met avocado en Hollandse garnalen",
    vanSchaap: ["200 g gepelde, gekookte Hollandse garnalen — vraag naar de actuele beschikbaarheid"],
    vanSupermarkt: [
      "4 sneden zuurdesembrood",
      "2 avocado's",
      "1 citroen",
      "1 el mayonaise",
      "Snuf cayennepeper",
      "1 el fijngeknipte bieslook",
      "4 radijsjes (optioneel)",
      "Zout en peper",
    ],
    bereidingswijze: [
      "Rooster het brood.",
      "Prak de avocado met citroensap, zout en peper.",
      "Meng de garnalen losjes met 1 el mayonaise en een snufje cayenne.",
      "Besmeer de toast met avocado en stapel de garnalen erop.",
      "Werk af met bieslook, citroenrasp en eventueel plakjes radijs.",
    ],
    verhaal: "Gebruik reeds gekookte en gepelde Hollandse garnalen. Avocado maakt de toast romig; citroen en bieslook zorgen voor frisheid.",
    seoKeywords: "toast garnalen avocado, hollandse garnalen recept, garnalen lunch recept",
  },
];
