import type { Metadata } from "next";
import { BEDRIJF, ADRES_REGEL } from "@/lib/bedrijf";
import { GEMEENTEN } from "@/lib/bezorging";
import { BEELD } from "@/lib/beeld";
export const LOCALES=["nl","en","de"] as const;
export type Locale=(typeof LOCALES)[number];
const ogLocales:Record<string,string>={nl:"nl_NL",en:"en_GB",de:"de_DE"};
export function alternates(locale:string,pad:string){const clean=pad==="/"?"":pad;return {canonical:`/${locale}${clean}`,languages:{...Object.fromEntries(LOCALES.map(l=>[l,`/${l}${clean}`])),"x-default":`/nl${clean}`}};}
interface PaginaSeo{locale:string;pad:string;title:string;description:string;geenIndex?:boolean;}
export function paginaMetadata({locale,pad,title,description,geenIndex}:PaginaSeo):Metadata{return {title,description,alternates:alternates(locale,pad),openGraph:{title,description,type:"website",siteName:BEDRIJF.naam,locale:ogLocales[locale],alternateLocale:LOCALES.filter(l=>l!==locale).map(l=>ogLocales[l]),url:`${BEDRIJF.domein}/${locale}${pad==="/"?"":pad}`,images:[{url:"/og-image.png",width:1200,height:630,alt:BEDRIJF.naam}]},twitter:{card:"summary_large_image",title,description,images:["/og-image.png"]},...(geenIndex?{robots:{index:false,follow:true}}:{})};}
interface EenTaalSeo{taal:Locale;pad:string;title:string;description:string;paren?:Partial<Record<Locale,string>>;}
export function eenTaalMetadata({taal,pad,title,description,paren}:EenTaalSeo):Metadata{const languages:Record<string,string>={[taal]:`/${taal}${pad}`};for(const [l,p]of Object.entries(paren??{}))languages[l]=`/${l}${p}`;languages["x-default"]=languages.nl??`/${taal}${pad}`;return {...paginaMetadata({locale:taal,pad,title,description}),alternates:{canonical:`/${taal}${pad}`,languages}};}
const address={"@type":"PostalAddress",streetAddress:BEDRIJF.adres.straat,addressLocality:BEDRIJF.adres.plaats,addressRegion:BEDRIJF.adres.provincie,postalCode:BEDRIJF.adres.postcode,addressCountry:"NL"};
const hours=[{"@type":"OpeningHoursSpecification",dayOfWeek:["Tuesday","Wednesday","Thursday","Friday"],opens:"09:00",closes:"18:00"},{"@type":"OpeningHoursSpecification",dayOfWeek:["Saturday"],opens:"09:00",closes:"17:00"}];
export function winkelSchema(locale:string){return {"@context":"https://schema.org","@type":"GroceryStore","@id":`${BEDRIJF.domein}/#winkel`,name:BEDRIJF.naam,url:`${BEDRIJF.domein}/${locale}`,telephone:BEDRIJF.telefoon.e164,address,geo:{"@type":"GeoCoordinates",latitude:BEDRIJF.geo.lat,longitude:BEDRIJF.geo.lng},hasMap:BEDRIJF.maps.profiel,foundingDate:BEDRIJF.opgericht,openingHoursSpecification:hours,...(BEELD.winkelGevel.bestand?{image:`${BEDRIJF.domein}${BEELD.winkelGevel.bestand}`}:{})};}
export function organisatieSchema(){return {"@context":"https://schema.org","@type":"Organization","@id":`${BEDRIJF.domein}/#organisatie`,name:BEDRIJF.naam,url:BEDRIJF.domein,foundingDate:BEDRIJF.opgericht,address,telephone:BEDRIJF.telefoon.e164,...(BEELD.logoBadge.bestand?{logo:`${BEDRIJF.domein}${BEELD.logoBadge.bestand}`}:{})};}
export function websiteSchema(locale:string){return {"@context":"https://schema.org","@type":"WebSite","@id":`${BEDRIJF.domein}/#website`,name:BEDRIJF.naam,url:BEDRIJF.domein,inLanguage:locale,publisher:{"@id":`${BEDRIJF.domein}/#organisatie`}};}
export function bezorgdienstSchema(locale:string){return {"@context":"https://schema.org","@type":"Service","@id":`${BEDRIJF.domein}/#bezorgdienst`,name:locale==="de"?"Fischlieferung am Donnerstag":locale==="en"?"Thursday fish delivery":"Visbezorging op donderdag",description:locale==="de"?"Frischer Fisch, Salate und Fischplatten. Ausschließlich donnerstags.":locale==="en"?"Fresh fish, salads and seafood platters. Thursdays only.":"Verse vis, salades en visschalen. Uitsluitend iedere donderdag.",provider:{"@id":`${BEDRIJF.domein}/#winkel`},areaServed:GEMEENTEN.map(g=>({"@type":"City",name:g.naam})),availableChannel:{"@type":"ServiceChannel",serviceUrl:`${BEDRIJF.domein}/${locale}/bezorgen`,servicePhone:{"@type":"ContactPoint",telephone:BEDRIJF.telefoon.e164},availableLanguage:["nl","en","de"]}};}
export function kruimelSchema(locale:string,items:{naam:string;pad:string}[]){return {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((k,i)=>({"@type":"ListItem",position:i+1,name:k.naam,item:`${BEDRIJF.domein}/${locale}${k.pad==="/"?"":k.pad}`}))};}
export function vraagSchema(items:{v:string;a:string}[]){return {"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(q=>({"@type":"Question",name:q.v,acceptedAnswer:{"@type":"Answer",text:q.a}}))};}
export { ADRES_REGEL };
