import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { Schema } from "@/components/Schema";
import { BEDRIJF } from "@/lib/bedrijf";
import { products } from "@/lib/assortiment-data";
import { localizeProduct } from "@/lib/product-localization";
import { productPhoto } from "@/lib/product-beeld";
import { ProductPhotoCredit } from "@/components/ProductPhotoCredit";
import { paginaMetadata, kruimelSchema, vraagSchema } from "@/lib/seo";
import { VarlaksFilm } from "@/components/shared/VarlaksFilm";
import { bestelContact } from "@/lib/bestel-contact";
const copy={
 nl:{label:"Bewuster kiezen · stap voor stap",title:"Biologische vis\nin Leiden.",intro:"Onze VÅRLAKS-zalm is de trots van de toonbank. Daarnaast kiezen we voor vis en garnalen met keurmerken zoals MSC en ASC. Nog niet alles kan zoals we het willen, maar het begin is er.",contact:"Vraag ons om advies",range:"Ontdek het assortiment",supplier:"Onze trots: VÅRLAKS-zalm",story:"VÅRLAKS brengt zalm uit het koude water van Noord-Noorwegen, boven de poolcirkel. Volgens de leverancier komt de zalm van familiebedrijven en is de herkomst volledig traceerbaar.",story2:"Wij vertellen u graag meer over de vis in onze toonbank. Vraag naar de actuele herkomst, beschikbaarheid en certificering van het product dat u wilt meenemen.",source:"Meer over VÅRLAKS",cert:"Biologisch, ASC of MSC?",certintro:"Dit zijn verschillende keurmerken. Een verhaal over duurzame vis is niet automatisch een biologische certificering.",bio:"Biologische kweek",biotext:"Biologisch gaat over gecertificeerde kweek volgens biologische regels. Vraag ons welke biologische producten op dit moment beschikbaar zijn en welk keurmerk ze dragen.",asc:"Verantwoorde kweek",asctext:"ASC is een keurmerk voor verantwoord gekweekte vis. Het is niet hetzelfde als biologisch. De certificering moet bij het specifieke product horen.",msc:"Verantwoorde wildvangst",msctext:"MSC is een keurmerk voor duurzame wildgevangen vis. Het gaat om de visserij en de traceerbaarheid in de keten.",end:"Een goede keuze maken we samen.",note:"Niet alles in onze toonbank is biologisch of gecertificeerd. We zijn trots op onze zalm en MSC-garnalen en zoeken ook voor andere vis naar goede keuzes. Stap voor stap maken we ons assortiment bewuster. We vertellen eerlijk welk keurmerk bij welk product hoort."},
 en:{label:"Origin matters",title:"Organic fish\nin Leiden.",intro:"Our VÅRLAKS salmon is the pride of our counter. We also choose fish and shrimp with MSC and ASC labels. Not everything is where we want it to be yet, but we have made a start.",contact:"Ask us for advice",range:"Explore our range",supplier:"Our salmon from VÅRLAKS",story:"VÅRLAKS sources salmon from the cold waters of Northern Norway, above the Arctic Circle. The supplier describes family-owned farms and fully traceable origins.",story2:"Ask us about the origin, availability and certification of the specific fish in our counter. We are happy to help you make a considered choice.",source:"More about VÅRLAKS",cert:"Organic, ASC or MSC?",certintro:"These are different certifications. A sustainability story does not automatically mean organic certification.",bio:"Organic aquaculture",biotext:"Organic refers to certified farming under organic rules. Ask which certified organic products are currently available.",asc:"Responsible aquaculture",asctext:"ASC certifies responsibly farmed seafood. It is not the same as organic and must apply to the specific product.",msc:"Responsible wild catch",msctext:"MSC is a label for sustainably caught wild seafood and traceability through the supply chain.",end:"Let us help you choose.",note:"Not everything in our counter is organic or certified. We are proud of our salmon and MSC shrimp, and keep looking for good choices for other fish. Step by step, we improve our range and explain which label applies to each product."},
 de:{label:"Die Herkunft zählt",title:"Bio-Fisch\nin Leiden.",intro:"Unser VÅRLAKS-Lachs ist der Stolz unserer Fischtheke. Daneben wählen wir Fisch und Garnelen mit MSC- und ASC-Siegeln. Noch ist nicht alles perfekt, aber der Anfang ist gemacht.",contact:"Lassen Sie sich beraten",range:"Sortiment entdecken",supplier:"Unser Lachs von VÅRLAKS",story:"VÅRLAKS bezieht Lachs aus den kalten Gewässern Nordnorwegens, oberhalb des Polarkreises. Der Anbieter beschreibt Familienbetriebe und eine vollständig rückverfolgbare Herkunft.",story2:"Fragen Sie uns nach Herkunft, Verfügbarkeit und Zertifizierung des konkreten Produkts in unserer Fischtheke. Wir beraten Sie gerne.",source:"Mehr über VÅRLAKS",cert:"Bio, ASC oder MSC?",certintro:"Diese Siegel sind unterschiedlich. Nachhaltigkeit bedeutet nicht automatisch eine Bio-Zertifizierung.",bio:"Biologische Aquakultur",biotext:"Bio bezeichnet eine zertifizierte Zucht nach biologischen Regeln. Fragen Sie uns nach den aktuell verfügbaren zertifizierten Bio-Produkten.",asc:"Verantwortungsvolle Zucht",asctext:"ASC steht für verantwortungsvoll gezüchteten Fisch. Es ist kein Bio-Siegel und muss für das konkrete Produkt gelten.",msc:"Nachhaltiger Wildfang",msctext:"MSC kennzeichnet nachhaltig gefangenen Wildfisch und die Rückverfolgbarkeit entlang der Lieferkette.",end:"Gemeinsam treffen wir eine gute Wahl.",note:"Nicht alles in unserer Fischtheke ist biologisch oder zertifiziert. Wir sind stolz auf unseren Lachs und unsere MSC-Garnelen und suchen weiter nach guten Möglichkeiten. Schritt für Schritt verbessern wir unser Sortiment und erklären ehrlich das jeweilige Siegel."}
};
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{
 const {locale}=await params; const c=copy[locale as keyof typeof copy]||copy.nl;
 return paginaMetadata({locale,pad:"/biologische-vis",title:c.title.replace("\n"," ")+" | Schaap’s Vishandel",description:c.intro});
}
export default async function Page({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params; const c=copy[locale as keyof typeof copy]||copy.nl;
 const labels = locale === "de" ? { cooking: "Kochen mit Lachs", recipes: "Lachsrezepte", more: "Mehr erfahren", faq: "Häufige Fragen", product: "Unser VÅRLAKS-Lachs", blog: "Herkunft und Siegel erklärt" } : locale === "en" ? { cooking: "Cook something good with salmon", recipes: "Salmon recipes", more: "Find out more", faq: "Common questions", product: "Our VÅRLAKS salmon", blog: "Origins and labels explained" } : { cooking: "Van goede vis naar een goed gerecht", recipes: "Zalmrecepten om mee te beginnen", more: "Lees meer", faq: "Veelgestelde vragen over biologische vis", product: "Onze VÅRLAKS-zalm", blog: "Herkomst en keurmerken uitgelegd" };
 const vragen = [{ v: c.cert, a: c.certintro + " " + c.biotext + " " + c.asctext + " " + c.msctext }, { v: c.contact + "?", a: c.note }];
 return <>
 <Schema data={kruimelSchema(locale, [{ naam: BEDRIJF.naamKort, pad: "/" }, { naam: c.title.replace("\n", " "), pad: "/biologische-vis" }])} />
 <Schema data={vraagSchema(vragen)} />
 <header className="fresh-hero"><div className="section-wrap fresh-hero-grid"><div><p className="kapitaal">{c.label}</p><h1>{c.title}</h1><p className="fresh-intro">{c.intro}</p><a className="knop knop-rood mt-7" href={bestelContact(locale).href}>{c.contact}</a></div><figure><Image width={1400} height={933} sizes="(max-width: 800px) 100vw, 50vw" src="/images/editorial/zalm.webp" alt={locale==="nl"?"Zalm met citroen en dille":locale==="de"?"Lachs mit Zitrone und Dill":"Salmon with lemon and dill"} fetchPriority="high"/></figure></div></header>
 <section className="story-section section-wrap"><div className="story-grid"><div><p className="kapitaal">{locale === "de" ? "VÅRLAKS · Nordnorwegen" : locale === "nl" ? "VÅRLAKS · Noord-Noorwegen" : "VÅRLAKS · Northern Norway"}</p><h2>{c.supplier}</h2><p>{c.story}</p><p>{c.story2}</p><a className="underline text-sm font-semibold" href="https://varlaks.no/" target="_blank" rel="noopener noreferrer">{c.source} ↗</a></div><VarlaksFilm locale={locale}/></div></section>
 <section className="fresh-contact"><div className="section-wrap"><h2>{c.cert}</h2><p className="mb-8">{c.certintro}</p><div className="cert-grid">{[[c.bio,c.biotext,"BIO"],[c.asc,c.asctext,"ASC"],[c.msc,c.msctext,"MSC"]].map(([title,text,label])=><article key={label}><p className="kapitaal mb-4">{label}</p><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="fresh-contact"><div className="section-wrap grid md:grid-cols-2 gap-10 items-center"><Image src="/images/producten-hd/hollandse-garnalen.webp" width={612} height={408} sizes="(max-width: 768px) 100vw, 50vw" alt={locale === "de" ? "Holländische Nordseegarnelen" : locale === "en" ? "Dutch North Sea shrimp" : "Hollandse Noordzeegarnalen"} className="w-full rounded-2xl" /><div><p className="kapitaal">MSC</p><h2>{locale === "de" ? "Holländische Garnelen mit MSC" : locale === "en" ? "MSC-certified Dutch shrimp" : "Hollandse garnalen met MSC"}</h2><p>{locale === "de" ? "Klein, aber voller Geschmack. Unsere holländischen Nordseegarnelen tragen das MSC-Siegel: ein bewusster Schritt zu nachhaltigerem Wildfang." : locale === "en" ? "Small in size, full of flavour. Our Dutch North Sea shrimp carry the MSC label: a considered step towards more sustainable wild catch." : "Klein van stuk, groots van smaak. Onze Hollandse garnalen hebben het MSC-keurmerk: een bewuste stap naar duurzamere wildvangst. Een Hollandse klassieker waar we trots op zijn."}</p><Link className="knop knop-lijn mt-5" href={`/${locale}/assortiment/hollandse-garnalen`}>{locale === "de" ? "Garnelen entdecken" : locale === "en" ? "Explore our shrimp" : "Bekijk de Hollandse garnalen"} →</Link></div></div></section>
 <section className="story-section section-wrap"><h2>{locale === "de" ? "Fisch mit Siegeln in unserem Sortiment" : locale === "en" ? "Fish with labels in our range" : "Vis met keurmerken in ons assortiment"}</h2><p className="max-w-3xl mb-8 leading-relaxed">{locale === "de" ? "Diese Produkte sind im Sortiment mit MSC oder ASC gekennzeichnet. Angebot und Zertifizierung können je nach Lieferung variieren; fragen Sie nach dem konkreten Produkt." : locale === "en" ? "These products are listed with MSC or ASC in our range. Supply and certification can vary by delivery; ask about the specific product you choose." : "Deze producten staan in ons assortiment met MSC of ASC aangeduid. Aanvoer en certificering kunnen per levering verschillen. Vraag ons naar het keurmerk van de vis die u kiest."}</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{products.filter(p => p.badge === "MSC" || p.badge === "ASC").map(bron => { const p = localizeProduct(bron,locale); const photo = productPhoto(p,locale); return <article key={p.slug} className="rounded-2xl border border-sky-100 overflow-hidden bg-white">{photo && <Image src={photo.src} alt={photo.alt} width={900} height={600} sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="w-full aspect-[3/2] object-contain" />}<div className="p-6"><ProductPhotoCredit photo={photo} locale={locale} /><p className="kapitaal mb-3">{p.badge}</p><h3 className="text-xl mb-4">{p.naam}</h3><Link className="underline font-semibold" href={`/${locale}/assortiment/${p.slug}`}>{locale === "de" ? "Produktinformationen" : locale === "en" ? "Product information" : "Productinformatie"} →</Link></div></article>; })}</div></section>
 <section className="fresh-contact"><div className="section-wrap"><h2 className="mb-7">{labels.faq}</h2>{vragen.map(q => <details className="py-5 border-b border-sky-200" key={q.v}><summary className="font-semibold cursor-pointer">{q.v}</summary><p className="mt-3 max-w-3xl">{q.a}</p></details>)}<div className="flex flex-wrap gap-5 mt-7"><Link className="underline font-semibold" href={`/${locale}/blog/wat-betekenen-msc-asc-en-het-eu-bio-logo`}>{labels.blog} →</Link><Link className="underline font-semibold" href={`/${locale}/assortiment/varlaks-zalm`}>{labels.product} →</Link></div></div></section>
 <section className="story-section section-wrap"><h2 className="max-w-2xl">{c.end}</h2><p className="max-w-2xl leading-relaxed mb-6">{c.note}</p><div className="flex flex-wrap gap-3"><a className="knop knop-rood" href={bestelContact(locale).href}>{c.contact}</a><Link className="knop knop-lijn" href={`/${locale}/assortiment`}>{c.range}</Link></div></section>
 </>;
}
