import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { paginaMetadata } from "@/lib/seo";
import { VarlaksFilm } from "@/components/shared/VarlaksFilm";
import { bestelContact } from "@/lib/bestel-contact";
const copy={
 nl:{label:"Herkomst doet ertoe",title:"Bewuste keuzes.\nGoede vis.",intro:"Vis kiezen begint bij weten waar die vandaan komt. Ontdek onze VÅRLAKS-zalm en wat keurmerken u wél vertellen.",contact:"Vraag ons om advies",range:"Ontdek het assortiment",supplier:"Onze zalm van VÅRLAKS",story:"VÅRLAKS brengt zalm uit het koude water van Noord-Noorwegen, boven de poolcirkel. Volgens de leverancier komt de zalm van familiebedrijven en is de herkomst volledig traceerbaar.",story2:"Wij vertellen u graag meer over de vis in onze toonbank. Vraag naar de actuele herkomst, beschikbaarheid en certificering van het product dat u wilt meenemen.",source:"Meer over VÅRLAKS",cert:"Biologisch, ASC of MSC?",certintro:"Dit zijn verschillende keurmerken. Een verhaal over duurzame vis is niet automatisch een biologische certificering.",bio:"Biologische kweek",biotext:"Biologisch gaat over gecertificeerde kweek volgens biologische regels. Vraag ons welke biologische producten op dit moment beschikbaar zijn en welk keurmerk ze dragen.",asc:"Verantwoorde kweek",asctext:"ASC is een keurmerk voor verantwoord gekweekte vis. Het is niet hetzelfde als biologisch. De certificering moet bij het specifieke product horen.",msc:"Verantwoorde wildvangst",msctext:"MSC is een keurmerk voor duurzame wildgevangen vis. Het gaat om de visserij en de traceerbaarheid in de keten.",end:"Een goede keuze maken we samen.",note:"Op zoek naar biologische vis of een bepaalde herkomst? Neem contact met ons op. We kijken graag wat mogelijk is. Visschalen kunt u online samenstellen en bestellen."},
 en:{label:"Origin matters",title:"Thoughtful choices.\nGreat fish.",intro:"Choosing fish starts with knowing its origin. Discover our VÅRLAKS salmon and what certification labels actually tell you.",contact:"Ask us for advice",range:"Explore our range",supplier:"Our salmon from VÅRLAKS",story:"VÅRLAKS sources salmon from the cold waters of Northern Norway, above the Arctic Circle. The supplier describes family-owned farms and fully traceable origins.",story2:"Ask us about the origin, availability and certification of the specific fish in our counter. We are happy to help you make a considered choice.",source:"More about VÅRLAKS",cert:"Organic, ASC or MSC?",certintro:"These are different certifications. A sustainability story does not automatically mean organic certification.",bio:"Organic aquaculture",biotext:"Organic refers to certified farming under organic rules. Ask which certified organic products are currently available.",asc:"Responsible aquaculture",asctext:"ASC certifies responsibly farmed seafood. It is not the same as organic and must apply to the specific product.",msc:"Responsible wild catch",msctext:"MSC is a label for sustainably caught wild seafood and traceability through the supply chain.",end:"Let us help you choose.",note:"Looking for organic fish or a particular origin? Contact us to discuss availability. Seafood platters can be created and ordered online."},
 de:{label:"Die Herkunft zählt",title:"Bewusst wählen.\nGuten Fisch genießen.",intro:"Guten Fisch zu wählen beginnt mit seiner Herkunft. Entdecken Sie unseren VÅRLAKS-Lachs und die Bedeutung der verschiedenen Siegel.",contact:"Lassen Sie sich beraten",range:"Sortiment entdecken",supplier:"Unser Lachs von VÅRLAKS",story:"VÅRLAKS bezieht Lachs aus den kalten Gewässern Nordnorwegens, oberhalb des Polarkreises. Der Anbieter beschreibt Familienbetriebe und eine vollständig rückverfolgbare Herkunft.",story2:"Fragen Sie uns nach Herkunft, Verfügbarkeit und Zertifizierung des konkreten Produkts in unserer Fischtheke. Wir beraten Sie gerne.",source:"Mehr über VÅRLAKS",cert:"Bio, ASC oder MSC?",certintro:"Diese Siegel sind unterschiedlich. Nachhaltigkeit bedeutet nicht automatisch eine Bio-Zertifizierung.",bio:"Biologische Aquakultur",biotext:"Bio bezeichnet eine zertifizierte Zucht nach biologischen Regeln. Fragen Sie uns nach den aktuell verfügbaren zertifizierten Bio-Produkten.",asc:"Verantwortungsvolle Zucht",asctext:"ASC steht für verantwortungsvoll gezüchteten Fisch. Es ist kein Bio-Siegel und muss für das konkrete Produkt gelten.",msc:"Nachhaltiger Wildfang",msctext:"MSC kennzeichnet nachhaltig gefangenen Wildfisch und die Rückverfolgbarkeit entlang der Lieferkette.",end:"Gemeinsam treffen wir eine gute Wahl.",note:"Suchen Sie Bio-Fisch oder eine bestimmte Herkunft? Kontaktieren Sie uns. Fischplatten können Sie online zusammenstellen und bestellen."}
};
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{
 const {locale}=await params; const c=copy[locale as keyof typeof copy]||copy.nl;
 return paginaMetadata({locale,pad:"/biologische-vis",title:c.cert+" | Schaap’s Vishandel Leiden",description:c.intro});
}
export default async function Page({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params; const c=copy[locale as keyof typeof copy]||copy.nl;
 return <>
 <header className="fresh-hero"><div className="section-wrap fresh-hero-grid"><div><p className="kapitaal">{c.label}</p><h1>{c.title}</h1><p className="fresh-intro">{c.intro}</p><a className="knop knop-rood mt-7" href={bestelContact(locale).href}>{c.contact}</a></div><figure><Image width={1400} height={933} sizes="(max-width: 800px) 100vw, 50vw" src="/images/editorial/zalm.webp" alt={locale==="nl"?"Zalm met citroen en dille":locale==="de"?"Lachs mit Zitrone und Dill":"Salmon with lemon and dill"} fetchPriority="high"/></figure></div></header>
 <section className="story-section section-wrap"><div className="story-grid"><div><p className="kapitaal">VÅRLAKS · Northern Norway</p><h2>{c.supplier}</h2><p>{c.story}</p><p>{c.story2}</p><a className="underline text-sm font-semibold" href="https://varlaks.no/" target="_blank" rel="noopener noreferrer">{c.source} ↗</a></div><VarlaksFilm locale={locale}/></div></section>
 <section className="fresh-contact"><div className="section-wrap"><h2>{c.cert}</h2><p className="mb-8">{c.certintro}</p><div className="cert-grid">{[[c.bio,c.biotext,"BIO"],[c.asc,c.asctext,"ASC"],[c.msc,c.msctext,"MSC"]].map(([title,text,label])=><article key={label}><p className="kapitaal mb-4">{label}</p><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="story-section section-wrap"><h2 className="max-w-2xl">{c.end}</h2><p className="max-w-2xl leading-relaxed mb-6">{c.note}</p><div className="flex flex-wrap gap-3"><a className="knop knop-rood" href={bestelContact(locale).href}>{c.contact}</a><Link className="knop knop-lijn" href={`/${locale}/assortiment`}>{c.range}</Link></div></section>
 </>;
}
